"""Browser integration suite. Python Playwright is a development-only dependency.
Uses localhost when allowed, or an in-memory document in restricted environments.
"""
from pathlib import Path
import json, os, zipfile, io, re, time
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'test-results'; OUT.mkdir(exist_ok=True)
results=[]
def check(name,condition,detail=None):
    if not condition: raise AssertionError(f'{name}: {detail}')
    results.append({'name':name,'passed':True,'detail':detail})
    print('PASS',name,flush=True)
with sync_playwright() as playwright:
    browser=playwright.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),headless=True,args=['--no-sandbox','--enable-unsafe-webgpu','--use-angle=swiftshader'])
    context=browser.new_context(viewport={'width':1600,'height':1000},device_scale_factor=1,accept_downloads=True)
    page=context.new_page(); page.set_default_timeout(8000)
    errors=[]; logs=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('console',lambda m:logs.append({'type':m.type,'text':m.text}) if m.type in ['error','warning'] else None)
    mode='in-memory'
    if os.environ.get('PAGEFORGE_TEST_URL'):
        page.goto(os.environ['PAGEFORGE_TEST_URL'],wait_until='domcontentloaded'); mode='http'
    else: page.set_content((ROOT/'index.html').read_text(),wait_until='domcontentloaded')
    page.wait_for_function('window.pageforge && window.pageforge.editor.doc')
    page.wait_for_timeout(800)
    editor=lambda:page.frame_locator('#design-frame')
    check('Application initializes',page.locator('html').get_attribute('data-ready')=='true')
    check('Seven sample files and four HTML pages',page.evaluate('pageforge.model.files.length')==7 and page.evaluate('pageforge.analyze().pages.length')==4)
    check('Shared CSS resolves in Design',editor().locator('body').evaluate('(e)=>getComputedStyle(e).backgroundColor')=='rgb(248, 248, 242)')
    check('Local SVG image resolves',editor().locator('.project-image img').evaluate('(e)=>e.complete && e.naturalWidth>0'))
    check('Honest active renderer label',page.evaluate("['WebGPU','Canvas 2D'].includes(pageforge.renderer.mode)"),page.locator('#renderer-status').inner_text())
    # Native contenteditable input with an actual keyboard operation.
    editor().locator('h1').click()
    page.evaluate("""()=>{const e=pageforge.editor;const h=e.doc.querySelector('h1');e.select(h);const r=e.doc.createRange();r.selectNodeContents(h);e.setRange(r)}""")
    page.keyboard.insert_text('A beautifully editable website.')
    page.wait_for_timeout(400)
    check('Native typing updates canonical HTML','A beautifully editable website.' in page.evaluate('pageforge.model.active.content'))
    page.locator('#undo-tool').click(); page.wait_for_timeout(200)
    check('Undo restores visual document','Spaces for the' in editor().locator('h1').inner_text())
    page.locator('#redo-tool').click(); page.wait_for_timeout(200)
    check('Redo reapplies native edit','A beautifully editable website.' in editor().locator('h1').inner_text())
    page.evaluate("""()=>{const e=pageforge.editor;const h=e.doc.querySelector('h1');e.select(h);const r=e.doc.createRange();r.setStart(h.firstChild,0);r.setEnd(h.firstChild,13);e.setRange(r)}""")
    page.locator('#format-toolbar [data-cmd=bold]').click()
    check('Range formatting creates semantic strong element',editor().locator('h1 strong').count()==1)
    page.evaluate("pageforge.editor.select(pageforge.editor.doc.querySelector('h1'))")
    page.locator('[data-attr=id]').fill('hero-title');page.locator('[data-attr=id]').press('Tab')
    check('Inspector edits attributes',editor().locator('h1').get_attribute('id')=='hero-title')
    page.locator('[data-css=padding]').fill('12');page.locator('[data-css=padding]').press('Tab')
    check('Inspector normalizes numeric CSS dimensions',editor().locator('h1').evaluate('(e)=>e.style.padding')=='12px')
    page.locator('[data-inspector=insert]').click()
    before=editor().locator('p').count()
    page.locator('[data-component=paragraph]').click()
    check('Component insertion changes real DOM',editor().locator('p').count()==before+1)
    page.evaluate("pageforge.editor.duplicate()")
    check('Element duplication works',editor().locator('p').count()==before+2)
    page.evaluate("pageforge.editor.remove()")
    check('Element deletion works',editor().locator('p').count()==before+1)
    page.locator('[data-inspector=layers]').click()
    check('DOM layers are real nodes',page.locator('.layer-row').count()>25)
    page.locator('.mode-tabs [data-mode=split]').click()
    source=page.locator('#source-input').input_value().replace('A beautifully','A synchronously')
    page.locator('#source-input').fill(source);page.wait_for_timeout(700)
    check('Split source updates visual view','synchronously' in editor().locator('h1').inner_text())
    page.locator('.mode-tabs [data-mode=code]').click()
    page.evaluate("pageforge.run('find')")
    page.locator('#find-input').fill('synchronously');page.locator('#replace-input').fill('professionally')
    page.locator('[data-cmd=replace-all]').click()
    check('Source find and replace works','professionally' in page.evaluate('pageforge.model.active.content'))
    page.locator('.mode-tabs [data-mode=preview]').click();page.wait_for_timeout(250)
    preview=page.frame_locator('#preview-frame')
    check('Preview shows authored HTML','professionally' in preview.locator('h1').inner_text())
    preview.get_by_role('link',name='Our work',exact=True).click();page.wait_for_timeout(350)
    check('Preview follows local project navigation',page.evaluate('pageforge.model.active.path')=='projects.html')
    check('Preview scripts execute in sandbox',preview.locator('[data-year]').inner_text()==str(time.localtime().tm_year))
    isolation=preview.locator('body').evaluate("()=>{try{return !!parent.document.body}catch(e){return e.name}}")
    check('Preview cannot read parent document',isolation=='SecurityError',isolation)
    page.locator('.mode-tabs [data-mode=design]').click();page.wait_for_timeout(200)
    editor().locator('td').first.click()
    rows=editor().locator('table tr').count()
    page.evaluate("pageforge.run('table-row')")
    check('Table row insertion',editor().locator('table tr').count()==rows+1)
    page.evaluate("pageforge.run('table-column')")
    check('Table column insertion',editor().locator('table tr').first.locator('th,td').count()==4)
    page.locator('[data-device="390"]').click()
    check('Responsive viewport uses real CSS width',page.locator('#design-frame').evaluate('(e)=>parseFloat(e.style.width)')==390)
    page.locator('[data-device="0"]').click()
    # Site management views, all backed by the project model.
    for view in ['folders','reports','navigation','hyperlinks','tasks']:
        page.locator(f'[data-view={view}]').click()
        check('Site view '+view,page.locator('#site-view').is_visible() and len(page.locator('#site-view').inner_text())>30)
    page.locator('#new-task-input').fill('Browser-tested task');page.locator('#new-task-input').press('Enter')
    check('Task creation',page.locator('.task-item').count()==4)
    page.locator('[data-task-id]').last.check()
    check('Task completion updates project',page.evaluate('pageforge.model.data.tasks.at(-1).done'))
    page.locator('[data-menu=File]').click();page.locator('#dropdown-menu [data-cmd=new]').click()
    page.locator('#modal [name=path]').fill('pages/test.html')
    page.locator('#modal [name=title]').fill('Browser-tested page')
    page.locator('#modal [name=template]').select_option('studio')
    page.locator('#modal button[value=ok]').click();page.wait_for_timeout(300)
    check('New nested HTML page',page.evaluate('pageforge.model.active.path')=='pages/test.html')
    check('Nested shared stylesheet resolves',editor().locator('body').evaluate('(e)=>getComputedStyle(e).backgroundColor')=='rgb(248, 248, 242)')
    page.locator('[data-menu=File]').click();page.locator('#dropdown-menu [data-cmd=rename]').click()
    page.locator('#modal [name=path]').fill('pages/renamed.html');page.locator('#modal button[value=ok]').click();page.wait_for_timeout(250)
    check('Rename file updates active path',page.evaluate('pageforge.model.active.path')=='pages/renamed.html')
    # All exported site files should be canonical, never editor runtime DOM.
    with page.expect_download() as dl:
        page.evaluate("pageforge.exportSite()")
    zip_data=Path(dl.value.path()).read_bytes();(OUT/'exported-site.zip').write_bytes(zip_data)
    with zipfile.ZipFile(io.BytesIO(zip_data)) as archive:
        check('Website ZIP is valid',archive.testzip() is None and len(archive.namelist())==8)
        exported=archive.read('index.html').decode()
        check('Export contains no runtime artifacts','data-pf-' not in exported and 'contenteditable="true"' not in exported)
        check('Original scripts and asset paths are preserved','src="scripts/site.js"' in exported and 'src="assets/pavilion.svg"' in exported)
    with page.expect_download() as dl:
        page.evaluate("pageforge.exportProject()")
    backup=Path(dl.value.path()).read_bytes();(OUT/'backup.pageforge').write_bytes(backup)
    check('Project backup preserves all files',len(json.loads(backup)['files'])==8)
    # Import ZIP through native file input, verify replacement and runtime.
    page.locator('#import-input').set_input_files({'name':'roundtrip.zip','mimeType':'application/zip','buffer':zip_data})
    page.locator('#modal button[value=ok]').click();page.wait_for_timeout(300)
    check('ZIP import round trip',page.evaluate('pageforge.model.files.length')==8)
    # Exported scripts remain inert in Design even after an imported document.
    page.evaluate("""async()=>{const a=pageforge;const content=a.model.active.content.replace('</body>','<script>window.__testExecuted=true;document.body.dataset.executed="yes";</script></body>');a.model.update(a.model.active.path,content,'Test script');await a.editor.load(a.model.active.path)}""")
    check('Authored script is disabled in Design',editor().locator('body').get_attribute('data-executed') is None)
    page.evaluate("pageforge.setMode('preview')")
    page.wait_for_timeout(300)
    check('Authored script runs in isolated Preview',page.frame_locator('#preview-frame').locator('body').get_attribute('data-executed')=='yes')
    check('No uncaught application JavaScript exceptions',not errors,errors)
    # Restore a clean sample for screenshots.
    page.locator('[data-menu=Help]').click();page.locator('#dropdown-menu [data-cmd=reset-demo]').click();page.locator('#modal button[value=ok]').click();page.wait_for_timeout(350)
    page.locator('[data-inspector=properties]').click();page.wait_for_timeout(7800)
    page.screenshot(path=str(OUT/'design.png'),full_page=True)
    page.locator('.mode-tabs [data-mode=split]').click();page.wait_for_timeout(250)
    page.screenshot(path=str(OUT/'split.png'),full_page=True)
    page.locator('.mode-tabs [data-mode=preview]').click();page.locator('[data-device="390"]').click();page.wait_for_timeout(250)
    page.screenshot(path=str(OUT/'mobile-preview.png'),full_page=True)
    output={'browser':browser.version,'mode':mode,'renderer':page.evaluate('pageforge.renderer.mode'),'storage':page.evaluate('pageforge.store.backend'),'passed':len(results),'results':results,'pageErrors':errors,'console':logs}
    (OUT/'browser-results.json').write_text(json.dumps(output,indent=2))
    print(json.dumps({k:v for k,v in output.items() if k not in ['results','console']},indent=2))
    context.close();browser.close()
