import { APP_VERSION, PROJECT_VERSION, LIMITS, escapeHTML, extension, isHTML, mimeType, isTextFile, normalizePath, resolvePath, relativePath, validateProject, ProjectModel, ProjectStore, downloadBlob, bytesFromFile, dataURI } from './core.js';
import { createZip, readZip } from './zip.js';
import { OverlayRenderer } from './renderer.js';
import { DocumentRuntime, VisualEditor } from './editor.js';
import { starterProject, blankPage, htmlDocument, componentLibrary } from './templates.js';
import { createShell, icon, tool, fileIcon } from './ui.js';
const $ = (selector,root=document)=>root.querySelector(selector);
const $$ = (selector,root=document)=>[...root.querySelectorAll(selector)];
const safeJSON = value=>escapeHTML(JSON.stringify(value));
const humanBytes=bytes=>bytes<1024?bytes+' B':bytes<1048576?(bytes/1024).toFixed(1)+' KB':(bytes/1048576).toFixed(1)+' MB';
const cap = value=>value.charAt(0).toUpperCase()+value.slice(1);
const attrInput=(label,name,value='',placeholder='')=>`<label class="property-row"><span>${label}</span><input data-attr="${name}" value="${escapeHTML(value)}" placeholder="${escapeHTML(placeholder)}" aria-label="${label}"></label>`;
const cssInput=(label,name,value='',placeholder='auto')=>`<label class="property-row"><span>${label}</span><input data-css="${name}" value="${escapeHTML(value)}" placeholder="${escapeHTML(placeholder)}" aria-label="${label}"></label>`;
const formField=(label,name,value='',type='text',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${escapeHTML(value)}" ${extra}></label>`;
const formatCommands=new Set(['bold','italic','underline','strike','left','center','right','justify','ul','ol','indent','outdent','clear']);
export class PageForgeApp {
  constructor(){this.mode='design';this.view='page';this.inspector='properties';this.device=0;this.zoom=1;this.boundaries=false;this.grid=false;this.openTabs=['index.html','styles/site.css'];this.collapsed=new Set();this.sourceTimer=0;this.autosaveTimer=0;this.paintFrame=0;this.saveChain=Promise.resolve();this.channelId=globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2);this.autosavePaused=false;this.persistedMode='IndexedDB';this.loading=false;this.settings={autosave:true,spellcheck:true,theme:'blue'};}
  async init(){
    document.body.innerHTML=createShell();
    try{this.settings={...this.settings,...JSON.parse(localStorage.getItem('pageforge-settings')||'{}')};}catch{}
    document.body.dataset.theme=this.settings.theme;
    this.store=await new ProjectStore().open();let data=null;try{data=await this.store.read();if(data)data=validateProject(data);}catch(e){this.toast('Saved project could not be loaded: '+e.message,true);}
    this.model=new ProjectModel(data||starterProject());this.model.savedRevision=data?0:-1;this.runtime=new DocumentRuntime(this.model);this.editor=new VisualEditor($('#design-frame'),this.model,this.runtime);this.openTabs=[this.model.active.path];if(this.model.get('styles/site.css')&&this.model.active.path!=='styles/site.css')this.openTabs.push('styles/site.css');
    this.renderer=new OverlayRenderer($('#overlay-canvas'),(mode,detail)=>{this.persistedMode=mode;$('#engine-badge span').textContent=mode==='WebGPU'?'WebGPU accelerated':'Canvas fallback';$('#engine-badge').title=detail;$('#renderer-status').textContent=mode==='WebGPU'?'WebGPU · on demand':'Canvas 2D · on demand';this.requestPaint();});
    this.bind();this.bindModel();this.bindEditor();this.renderTree();this.renderTabs();this.renderHeader();this.renderInspector();this.renderer.init();
    await this.openFile(this.model.active.path,false);this.renderSaveState();new ResizeObserver(()=>this.layout()).observe($('#design-stage'));this.layout();
    if(typeof BroadcastChannel!=='undefined'){this.broadcast=new BroadcastChannel('pageforge-project');this.broadcast.onmessage=e=>{if(e.data?.source!==this.channelId&&e.data?.type==='saved'&&!this.autosavePaused){this.autosavePaused=true;this.toast('Another tab saved this project. Autosave is paused here to prevent overwriting it.',true);this.renderSaveState();}};}
    if(!data)this.scheduleSave();if(this.store.backend==='memory')this.toast('Local storage is unavailable. Export your project to keep your work.',true);
    window.pageforge=this;document.documentElement.dataset.ready='true';
  }
  bindModel(){this.model.addEventListener('change',event=>{const {kind,path}=event.detail;this.renderHeader();this.renderTabs();if(['add','remove','rename','load','activate'].includes(kind))this.renderTree();if(kind==='edit'||kind==='history'){if(path===this.model.active.path&&document.activeElement!==$('#source-input'))this.renderSource();}if(kind!=='load')this.scheduleSave();this.renderSaveState();if(this.view!=='page'&&kind!=='activate')this.renderSiteView();});}
  bindEditor(){
    this.editor.addEventListener('selection',()=>{this.renderBreadcrumbs();this.updateFormatting();if(!$('#inspector-content').contains(document.activeElement))this.renderInspector();this.requestPaint();});
    this.editor.addEventListener('paint',()=>this.requestPaint());
    this.editor.addEventListener('commit',()=>{this.renderSource();this.renderBreadcrumbs();if(this.inspector==='layers')this.renderInspector();});
    this.editor.addEventListener('load',()=>{this.editor.doc.body.spellcheck=this.settings.spellcheck;this.layout();this.renderInspector();this.renderBreadcrumbs();});
    this.editor.addEventListener('shortcut',e=>this.run(e.detail.command));
    this.editor.addEventListener('navigate',e=>this.openFile(e.detail.path));
    this.editor.addEventListener('image',()=>this.run('image'));
    this.editor.addEventListener('dropcomponent',e=>this.insertComponent(e.detail.id));
    this.editor.addEventListener('dropnode',e=>this.editor.moveNode(e.detail.path,e.detail.target));
  }
  bind(){
    document.addEventListener('pointerdown',e=>{const command=e.target.closest('[data-cmd]');if(command&&!e.target.closest('dialog')&&command.closest('.toolbar,.element-actions'))e.preventDefault();if(!e.target.closest('.dropdown-menu,[data-menu]'))this.closeMenu();});
    document.addEventListener('click',e=>{
      const menu=e.target.closest('button[data-menu]');if(menu){this.openMenu(menu);return;}
      const cmd=e.target.closest('[data-cmd]');if(cmd){e.preventDefault();this.closeMenu();this.run(cmd.dataset.cmd,cmd.dataset.value);return;}
      const mode=e.target.closest('[data-mode]');if(mode?.tagName==='BUTTON'){this.setMode(mode.dataset.mode);return;}
      const view=e.target.closest('[data-view]');if(view){this.setView(view.dataset.view);return;}
      const device=e.target.closest('[data-device]');if(device){this.setDevice(Number(device.dataset.device));return;}
      const inspector=e.target.closest('[data-inspector]');if(inspector){this.inspector=inspector.dataset.inspector;this.renderInspector();return;}
      const closeTab=e.target.closest('[data-close-tab]');if(closeTab){this.closeTab(closeTab.dataset.closeTab);return;}
      const tab=e.target.closest('[data-tab]');if(tab){tab.dataset.tab==='website'?this.setView('website'):this.openFile(tab.dataset.tab);return;}
      const file=e.target.closest('[data-file]');if(file){this.openFile(file.dataset.file);return;}
      const folder=e.target.closest('[data-folder]');if(folder){const p=folder.dataset.folder;this.collapsed.has(p)?this.collapsed.delete(p):this.collapsed.add(p);this.renderTree();return;}
      const component=e.target.closest('[data-component]');if(component){this.insertComponent(component.dataset.component);return;}
      const path=e.target.closest('[data-node-path]');if(path){const el=this.editor.fromPath(JSON.parse(path.dataset.nodePath));if(el){this.editor.select(el);el.scrollIntoView({block:'nearest'});this.requestPaint();}return;}
      const taskDelete=e.target.closest('[data-delete-task]');if(taskDelete){this.model.data.tasks=this.model.data.tasks.filter(t=>t.id!==taskDelete.dataset.deleteTask);this.touch('Delete task');this.renderSiteView();return;}
      const inspectIssue=e.target.closest('[data-issue-path]');if(inspectIssue)this.openFile(inspectIssue.dataset.issuePath);
    });
    document.addEventListener('change',e=>{
      const t=e.target;
      if(t.matches('[data-css]')){let value=t.value.trim();const name=t.dataset.css;if(value&&/^(width|height|padding|margin|gap|font-size|border-radius)$/.test(name)&&/^\d+(\.\d+)?$/.test(value))value+='px';if(value&&!CSS.supports(name,value)){this.toast('Not a valid CSS value for '+name,true);return;}this.editor.setProperty(name,value);}
      else if(t.matches('[data-attr]')){const name=t.dataset.attr,value=t.value;if(['href','src','poster'].includes(name)&&/^\s*(javascript|vbscript|data:text\/html):/i.test(value)){this.toast('Unsafe URL protocol.',true);return;}this.editor.setProperty(name,value,true);}
      else if(t.matches('[data-task-id]')){const task=this.model.data.tasks.find(task=>task.id===t.dataset.taskId);if(task){task.done=t.checked;this.touch('Update task');this.renderSiteView();}}
    });
    document.addEventListener('dragstart',e=>{const component=e.target.closest('[data-component]');if(component){e.dataTransfer.setData('application/x-pageforge-component',component.dataset.component);e.dataTransfer.effectAllowed='copy';}const layer=e.target.closest('.layer-row[data-node-path]');if(layer){e.dataTransfer.setData('application/x-pageforge-node',layer.dataset.nodePath);e.dataTransfer.effectAllowed='move';}});
    $('#file-filter').addEventListener('input',()=>this.renderTree());
    $('#block-format').addEventListener('change',e=>this.editor.format('block',e.target.value));
    $('#font-family').addEventListener('change',e=>this.editor.format('font',e.target.value));
    $('#font-size').addEventListener('change',e=>this.editor.format('size',e.target.value));
    $('#text-color').addEventListener('change',e=>this.editor.format('color',e.target.value));
    $('#highlight-color').addEventListener('change',e=>this.editor.format('highlight',e.target.value));
    $('#viewport-width').addEventListener('change',e=>this.setDevice(Number(e.target.value)));
    $('#zoom-level').addEventListener('change',e=>{this.zoom=Number(e.target.value);this.layout();});
    $('#source-input').addEventListener('input',()=>{this.renderHighlight();clearTimeout(this.sourceTimer);this.sourceTimer=setTimeout(()=>this.commitSource(),350);this.sourcePosition();});
    $('#source-input').addEventListener('scroll',()=>{const s=$('#source-input');$('#syntax-highlight').scrollTop=s.scrollTop;$('#syntax-highlight').scrollLeft=s.scrollLeft;$('#line-numbers').scrollTop=s.scrollTop;});
    $('#source-input').addEventListener('click',()=>this.sourcePosition());$('#source-input').addEventListener('keyup',()=>this.sourcePosition());
    $('#source-input').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const t=e.target,start=t.selectionStart,end=t.selectionEnd;t.setRangeText('  ',start,end,'end');t.dispatchEvent(new Event('input'));}});
    $('#find-input').addEventListener('input',()=>this.updateFindCount());$('#find-input').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();this.findNext();}if(e.key==='Escape')this.run('close-find');});
    $('#import-input').addEventListener('change',e=>{this.importFiles([...e.target.files]);e.target.value='';});
    $('#image-import-input').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;try{const f=await this.importSingle(files[0],'assets/');if($('#modal').open&&$('#modal [name=src]'))$('#modal [name=src]').value=relativePath(this.model.active.path,f.path);else{await this.ensureDesign();this.editor.insertHTML(`<img src="${escapeHTML(relativePath(this.model.active.path,f.path))}" alt="${escapeHTML(files[0].name.replace(/\.[^.]+$/,''))}" style="max-width:100%;height:auto">`,'Insert image');}}catch(error){this.toast(error.message,true);}e.target.value='';});
    document.addEventListener('keydown',e=>this.keydown(e));
    window.addEventListener('message',e=>{if(e.source!==$('#preview-frame').contentWindow||e.data?.channel!==this.channelId)return;if(e.data.type==='pageforge:navigate'&&typeof e.data.path==='string'&&this.model.get(e.data.path)&&isHTML(e.data.path))this.openFile(e.data.path);else if(e.data.type==='pageforge:preview-error')this.toast('Preview script: '+String(e.data.message).slice(0,250),true);});
    window.addEventListener('beforeunload',e=>{this.flush();if(this.model.revision!==this.model.savedRevision){e.preventDefault();e.returnValue='';}});
    document.addEventListener('visibilitychange',()=>{if(document.hidden){this.flush();if(this.settings.autosave&&!this.autosavePaused)this.saveNow(false);}});
    $('#resize-handles').addEventListener('pointerdown',e=>this.beginResize(e));
    $('#split-handle').addEventListener('pointerdown',e=>{e.preventDefault();const handle=e.currentTarget;handle.setPointerCapture(e.pointerId);const total=$('#editor-workspace').getBoundingClientRect();const move=event=>{$('#source-panel').style.height=Math.max(100,Math.min(total.height-130,event.clientY-total.top))+'px';this.layout();};const up=()=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',up);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',up,{once:true});});
  }
  keydown(e){if($('#modal').open)return;const mod=e.ctrlKey||e.metaKey;let cmd=null;if(mod)cmd=({s:'save',o:'import',n:'new',z:e.shiftKey?'redo':'undo',y:'redo',k:'link',f:'find'})[e.key.toLowerCase()];if(mod&&e.key.toLowerCase()==='d'&&!e.target.matches('input,textarea'))cmd='duplicate';if(e.key==='F1')cmd='help';if(e.key==='F5')cmd='preview';if(mod&&e.key==='Enter')cmd=this.mode==='preview'?'design':'preview';if(e.key==='Escape')this.closeMenu();if(cmd){e.preventDefault();this.run(cmd);}}
  async run(command,value){try{
    if(formatCommands.has(command)){await this.ensureDesign();this.editor.format(command);return;}
    switch(command){
      case 'new': return await this.newFile();
      case 'import': $('#import-input').click();break;
      case 'save': await this.saveNow(true);break;
      case 'save-project': this.exportProject();break;
      case 'export-file': this.exportFile();break;
      case 'export-site': this.exportSite();break;
      case 'publish': await this.publishDialog();break;
      case 'undo':case 'redo': await this.history(command);break;
      case 'design':case 'split':case 'code':case 'preview': await this.setMode(command);break;
      case 'folders':case 'reports':case 'navigation':case 'hyperlinks':case 'tasks':case 'website':this.setView(command);break;
      case 'link':await this.linkDialog();break;
      case 'image':await this.imageDialog();break;
      case 'table':await this.tableDialog();break;
      case 'table-row':case 'table-column':case 'table-delete-row':case 'table-delete-column':await this.ensureDesign();this.editor.table(command.replace('table-',''));break;
      case 'html':await this.htmlDialog();break;
      case 'component':this.inspector='insert';$('#workspace').classList.remove('hide-inspector');this.renderInspector();break;
      case 'insert-heading':case 'insert-paragraph':case 'insert-divider':case 'insert-form':await this.insertComponent(command.replace('insert-',''));break;
      case 'duplicate':await this.ensureDesign();this.editor.duplicate();break;
      case 'delete-element':await this.ensureDesign();this.editor.remove();break;
      case 'move-up':this.editor.move(-1);break;
      case 'move-down':this.editor.move(1);break;
      case 'select-parent':this.editor.select(this.editor.selected?.parentElement);break;
      case 'select-all':if(this.mode==='code')$('#source-input').select();else if(this.editor.doc){const r=this.editor.doc.createRange();r.selectNodeContents(this.editor.doc.body);this.editor.setRange(r);}break;
      case 'copy':case 'cut':await this.copy(command==='cut');break;
      case 'paste':await this.paste();break;
      case 'rename':await this.renameFile(value||this.model.active.path);break;
      case 'delete-file':await this.deleteFile(value||this.model.active.path);break;
      case 'page-properties':await this.pageProperties();break;
      case 'find':await this.showFind();break;
      case 'find-next':this.findNext();break;
      case 'replace-one':this.replace(false);break;
      case 'replace-all':this.replace(true);break;
      case 'close-find':$('#find-bar').hidden=true;break;
      case 'format-code':this.formatCode();break;
      case 'boundaries':this.boundaries=!this.boundaries;$('#boundaries-tool').classList.toggle('active',this.boundaries);this.requestPaint();this.toast('Element boundaries '+(this.boundaries?'shown':'hidden'));break;
      case 'grid':this.grid=!this.grid;this.requestPaint();break;
      case 'toggle-folders':$('#workspace').classList.toggle('hide-folders');this.layout();break;
      case 'toggle-inspector':$('#workspace').classList.toggle('hide-inspector');this.layout();break;
      case 'next-tab':{const index=this.openTabs.indexOf(this.model.active.path);await this.openFile(this.openTabs[(index+1)%this.openTabs.length]);break;}
      case 'close-tab':this.closeTab(this.model.active.path);break;
      case 'reset-layout':$('#workspace').classList.remove('hide-inspector','hide-folders');this.device=0;this.zoom=1;$('#zoom-level').value='1';this.setDevice(0);this.inspector='properties';this.renderInspector();this.setMode('design');break;
      case 'refresh':if(this.view==='page'){if(this.mode==='preview')this.renderPreview();else await this.editor.load(this.model.active.path);}else this.renderSiteView();break;
      case 'add-task':this.addTask();break;
      case 'settings':await this.settingsDialog();break;
      case 'help':await this.helpDialog();break;
      case 'shortcuts':await this.shortcutsDialog();break;
      case 'about':await this.aboutDialog();break;
      case 'reset-demo':await this.resetDemo();break;
      case 'upload-image':$('#image-import-input').click();break;
      default:if(command?.startsWith('component:'))await this.insertComponent(command.split(':')[1]);
    }
  }catch(error){console.error('PageForge:',error);this.toast(error.message||'The operation could not be completed.',true);}}
  renderHeader(){const title=this.model.data.name;$('#project-title').textContent=title;$('#site-root-name').textContent=title;document.title=title+' — PageForge Studio';$('#document-location').textContent=this.model.active.path;$('#file-type-badge').textContent=extension(this.model.active.path).toUpperCase();$('#status-file-count').textContent=this.model.files.length+' files';$('#undo-tool').disabled=!this.model.history?.canUndo;$('#redo-tool').disabled=!this.model.history?.canRedo;}
  renderTree(){const filter=$('#file-filter').value.trim().toLowerCase();const root={folders:new Map(),files:[]};for(const file of this.model.files){if(filter&&!file.path.toLowerCase().includes(filter))continue;let node=root;const parts=file.path.split('/'),name=parts.pop();for(const p of parts){if(!node.folders.has(p))node.folders.set(p,{folders:new Map(),files:[]});node=node.folders.get(p);}node.files.push({...file,name});}
    const render=(node,depth=0,prefix='')=>{let result='';for(const [name,child] of [...node.folders].sort(([a],[b])=>a.localeCompare(b))){const path=prefix+name,closed=this.collapsed.has(path)&&!filter;result+=`<button class="folder-row" role="treeitem" aria-expanded="${!closed}" data-folder="${escapeHTML(path)}" style="padding-left:${depth*12+4}px"><span class="expand-arrow">${closed?'▸':'▾'}</span>${icon(closed?'folder':'folderOpen')}<span>${escapeHTML(name)}</span></button>`;if(!closed)result+=render(child,depth+1,path+'/');}for(const f of node.files.sort((a,b)=>a.name.localeCompare(b.name))){result+=`<button class="file-row ${fileIcon(f.path)} ${f.path===this.model.active.path?'active':''}" role="treeitem" aria-selected="${f.path===this.model.active.path}" data-file="${escapeHTML(f.path)}" title="${escapeHTML(f.path)}" style="padding-left:${depth*12+17}px">${icon(fileIcon(f.path))}<span>${escapeHTML(f.name)}</span>${f.path==='index.html'?icon('home','home-mark'):''}</button>`;}return result;};$('#file-tree').innerHTML=render(root)||'<p class="panel-description">No matching files.</p>';}
  renderTabs(){this.openTabs=this.openTabs.filter(p=>this.model.get(p));if(!this.openTabs.includes(this.model.active.path))this.openTabs.push(this.model.active.path);$('#document-tabs').innerHTML=`<div class="document-tab ${this.view!=='page'?'active':''}" data-tab="website" role="button" tabindex="0">${icon('globe')} Web Site</div>`+this.openTabs.map(path=>`<div class="document-tab ${path===this.model.active.path&&this.view==='page'?'active':''}" data-tab="${escapeHTML(path)}" role="button" tabindex="0">${icon(fileIcon(path))}<span>${escapeHTML(path.split('/').pop())}</span><button class="tab-close" data-close-tab="${escapeHTML(path)}" aria-label="Close ${escapeHTML(path)}">${icon('close')}</button></div>`).join('')+`<button class="tab-add" data-cmd="new" aria-label="New file">${icon('plus')}</button>`;}
  async openFile(path,activate=true){if(!path||!this.model.get(path))return;this.flush();if(activate)this.model.activate(path);this.view='page';this.renderViewState();this.renderTree();this.renderTabs();this.renderHeader();this.renderSource(true);if(isHTML(path)){if(this.mode==='preview')this.renderPreview();else await this.editor.load(path);}else{this.mode='code';this.renderModeState();this.editor.selected=null;this.renderBreadcrumbs();this.renderInspector();}this.layout();}
  closeTab(path){this.flush();if(this.openTabs.length<=1){this.setView('website');return;}const i=this.openTabs.indexOf(path);this.openTabs=this.openTabs.filter(p=>p!==path);if(path===this.model.active.path)this.openFile(this.openTabs[Math.max(0,i-1)]);else this.renderTabs();}
  flush(){if(this.sourceTimer){clearTimeout(this.sourceTimer);this.sourceTimer=0;this.commitSource(false);}this.editor?.flush();}
  async ensureDesign(){if(!isHTML(this.model.active.path))throw new Error('Open an HTML page to use the visual editor.');if(this.view!=='page'||this.mode==='code'||this.mode==='preview')await this.setMode('design');if(!this.editor.doc||this.editor.path!==this.model.active.path)await this.editor.load(this.model.active.path);}
  async setMode(mode){if(!['design','split','code','preview'].includes(mode))return;this.flush();if(!isHTML(this.model.active.path)&&mode!=='code'){this.toast('Visual views are available for HTML pages. Open an HTML file first.',true);return;}const previous=this.mode;this.mode=mode;this.view='page';this.renderViewState();this.renderModeState();this.renderTabs();if(mode==='preview')this.renderPreview();else if(mode==='design'||mode==='split'){if(previous==='code'||previous==='preview'||this.editor.path!==this.model.active.path)await this.editor.load(this.model.active.path);}if(mode==='code'||mode==='split')this.renderSource(true);this.renderInspector();this.layout();}
  renderModeState(){$('#editor-workspace').dataset.mode=this.mode;$$('.mode-tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.mode===this.mode);b.setAttribute('aria-selected',String(b.dataset.mode===this.mode));});const preview=this.mode==='preview';$('#design-frame').hidden=preview;$('#preview-frame').hidden=!preview;$('#preview-notice').hidden=!preview;$('#format-toolbar').classList.toggle('inactive',this.mode==='code'||preview);$('#document-hint').textContent=preview?'Sandboxed preview · click links to navigate':this.mode==='code'?'Source is the document · changes save automatically':'Click to edit · Esc to select parent';if(preview||this.mode==='code'){this.renderer.begin();this.renderer.draw();$('#selection-label').hidden=true;$('#resize-handles').innerHTML='';}}
  setView(view){this.flush();this.view=view;this.renderViewState();this.renderTabs();if(view!=='page')this.renderSiteView();else this.layout();}
  renderViewState(){$$('.view-button').forEach(b=>b.classList.toggle('active',b.dataset.view===this.view));$('#site-view').hidden=this.view==='page';this.renderModeState();}
  setDevice(width){this.device=width;$('#viewport-width').value=String(width);$$('[data-device]').forEach(b=>b.classList.toggle('active',Number(b.dataset.device)===width));this.layout();}
  layout(){const stage=$('#design-stage');if(!stage||stage.clientWidth===0)return;const available=Math.max(220,stage.clientWidth-48),height=Math.max(180,stage.clientHeight-48);const width=this.device?this.device*this.zoom:available;const logicalWidth=width/this.zoom,logicalHeight=height/this.zoom;const sheet=$('#sheet');sheet.style.width=width+'px';sheet.style.height=height+'px';for(const frame of [$('#design-frame'),$('#preview-frame')]){frame.style.width=logicalWidth+'px';frame.style.height=logicalHeight+'px';frame.style.transform=`scale(${this.zoom})`;}
    this.renderer.resize(width,height);this.updateFormatting();$('#viewport-status').textContent=Math.round(logicalWidth)+' × '+Math.round(logicalHeight);$('#ruler').innerHTML=Array.from({length:Math.ceil(available/100)+1},(_,i)=>`<span style="left:${i*100}px">${Math.round(i*100/this.zoom)}</span>`).join('');this.requestPaint();}
  requestPaint(){if(this.paintFrame)return;this.paintFrame=requestAnimationFrame(()=>{this.paintFrame=0;this.paint();});}
  paint(){if(!this.renderer)return;this.renderer.begin();const active=this.view==='page'&&(this.mode==='design'||this.mode==='split');const selected=this.editor.selected;if(!active||!this.editor.doc){this.renderer.draw();$('#selection-label').hidden=true;$('#resize-handles').innerHTML='';return;}
    const w=this.renderer.width,h=this.renderer.height,z=this.zoom;
    if(this.grid){for(let x=0;x<w;x+=20*z)this.renderer.rect(x,0,1,h,[.35,.5,.7,.1]);for(let y=0;y<h;y+=20*z)this.renderer.rect(0,y,w,1,[.35,.5,.7,.1]);}
    if(this.boundaries){for(const el of [...this.editor.doc.body.querySelectorAll('section,article,div,p,h1,h2,h3,figure,table,td,th,header,footer,nav')].slice(0,700)){const r=el.getBoundingClientRect();if(r.width&&r.height&&r.bottom>0&&r.top*z<h)this.renderer.border({x:r.x*z,y:r.y*z,width:r.width*z,height:r.height*z},[.3,.5,.8,.23]);}}
    if(selected?.isConnected){const r=selected.getBoundingClientRect(),rect={x:r.x*z,y:r.y*z,width:r.width*z,height:r.height*z};if(rect.width&&rect.height&&r.bottom>0&&rect.y<h){this.renderer.border(rect,[.19,.43,.81,1],1);const label=$('#selection-label');label.hidden=false;label.textContent=selected.tagName.toLowerCase()+(selected.id?'#'+selected.id:selected.classList.length?'.'+selected.classList[0]:'');label.style.left=Math.max(0,Math.min(w-130,rect.x))+'px';label.style.top=Math.max(0,rect.y-19)+'px';const positions={nw:[0,0],n:[.5,0],ne:[1,0],e:[1,.5],se:[1,1],s:[.5,1],sw:[0,1],w:[0,.5]};if(!this.resizing){$('#resize-handles').innerHTML=selected===this.editor.doc.body?'':Object.entries(positions).filter(([,p])=>rect.y+p[1]*rect.height>=0&&rect.y+p[1]*rect.height<=h).map(([handle,p])=>`<button class="resize-handle" aria-label="Resize ${handle}" data-handle="${handle}" style="left:${rect.x+p[0]*rect.width}px;top:${rect.y+p[1]*rect.height}px"></button>`).join('');}$('#selection-dimensions').textContent=Math.round(r.width)+' × '+Math.round(r.height);}else{$('#selection-label').hidden=true;$('#resize-handles').innerHTML='';}}else{$('#selection-label').hidden=true;$('#resize-handles').innerHTML='';}this.renderer.draw();}
  beginResize(e){const handle=e.target.closest('[data-handle]');if(!handle||!this.editor.selected)return;e.preventDefault();this.editor.flush();const el=this.editor.selected,r=el.getBoundingClientRect(),style=this.editor.frame.contentWindow.getComputedStyle(el);const contentBox=style.boxSizing!=='border-box';const extrasX=contentBox?parseFloat(style.paddingLeft)+parseFloat(style.paddingRight)+parseFloat(style.borderLeftWidth)+parseFloat(style.borderRightWidth):0,extrasY=contentBox?parseFloat(style.paddingTop)+parseFloat(style.paddingBottom)+parseFloat(style.borderTopWidth)+parseFloat(style.borderBottomWidth):0;const x=e.clientX,y=e.clientY,direction=handle.dataset.handle,original=el.getAttribute('style');this.resizing=true;$('#resize-shield').hidden=false;handle.setPointerCapture(e.pointerId);const move=event=>{const dx=(event.clientX-x)/this.zoom,dy=(event.clientY-y)/this.zoom;if(/[ew]/.test(direction))el.style.width=Math.max(8,r.width-extrasX+dx*(direction.includes('w')?-1:1))+'px';if(/[ns]/.test(direction))el.style.height=Math.max(8,r.height-extrasY+dy*(direction.includes('n')?-1:1))+'px';this.requestPaint();};const end=event=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',end);handle.removeEventListener('pointercancel',end);this.resizing=false;$('#resize-shield').hidden=true;if(event.type==='pointercancel'){if(original===null)el.removeAttribute('style');else el.setAttribute('style',original);}else this.editor.commit('Resize element');this.renderInspector();this.requestPaint();};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);}
  renderBreadcrumbs(){const el=this.editor.selected,path=[];if(el&&isHTML(this.model.active.path)&&this.editor.doc?.body.contains(el)){let node=el;while(node&&node!==this.editor.doc.documentElement){path.unshift(node);node=node.parentElement;}}$('#tag-path').innerHTML=path.map((node,i)=>`${i?'<span class="tag-arrow">›</span>':''}<button data-node-path="${safeJSON(this.editor.nodePath(node))}">&lt;${node.tagName.toLowerCase()}${node.id?'#'+escapeHTML(node.id):node.classList.length?'.'+escapeHTML(node.classList[0]):''}&gt;</button>`).join('');if(!path.length)$('#selection-dimensions').textContent='';}
  updateFormatting(){const el=this.editor.selected;if(!el||!el.isConnected)return;const style=this.editor.frame.contentWindow.getComputedStyle(el);const values={bold:Number(style.fontWeight)>=600,italic:style.fontStyle==='italic',underline:style.textDecorationLine.includes('underline'),left:['start','left'].includes(style.textAlign),center:style.textAlign==='center',right:style.textAlign==='right',justify:style.textAlign==='justify',ul:!!el.closest('ul'),ol:!!el.closest('ol')};for(const [key,value] of Object.entries(values)){const b=$(`#format-toolbar [data-cmd="${key}"]`);if(b)b.classList.toggle('active',value);}const block=this.editor.block();if(block&&$('#block-format option[value="'+block.tagName.toLowerCase()+'"]'))$('#block-format').value=block.tagName.toLowerCase();const fontSize=Math.round(parseFloat(style.fontSize))+'px';const sizeSelect=$('#font-size');if(![...sizeSelect.options].some(o=>o.value===fontSize)){sizeSelect.querySelector('[data-dynamic]')?.remove();const option=new Option(Math.round(parseFloat(style.fontSize)),fontSize);option.dataset.dynamic='';sizeSelect.add(option);}sizeSelect.value=fontSize;const family=$('#font-family');const font=[...family.options].find(o=>style.fontFamily.toLowerCase().startsWith(o.value.split(',')[0].replaceAll("'",'').toLowerCase()));if(font)family.value=font.value;}
  renderInspector(){const root=$('#inspector-content');$$('[data-inspector]').forEach(b=>{b.classList.toggle('active',b.dataset.inspector===this.inspector);b.setAttribute('aria-selected',String(b.dataset.inspector===this.inspector));});if(this.inspector==='insert'){root.innerHTML='<p class="panel-description">Click to insert after the selected element, or drag a component onto the page.</p>'+['Text','Layout','Media','Elements'].map(group=>`<div class="insert-group-heading">${group}</div><div class="insert-grid">${componentLibrary.filter(c=>c.group===group).map(c=>`<button class="component-tile" data-component="${c.id}" draggable="true">${icon(c.icon)}<span>${c.name}</span></button>`).join('')}</div>`).join('');return;}
    const el=this.editor.selected;if(!this.editor.doc||!isHTML(this.model.active.path)||this.mode==='preview'){root.innerHTML=`<div class="empty-properties">${icon(this.mode==='preview'?'preview':'code')}<strong>${this.mode==='preview'?'Preview mode':'Source file'}</strong><p>${this.mode==='preview'?'Switch to Design to select and edit elements.':'Open an HTML page to use visual properties and the element tree.'}</p><button class="secondary-button" data-cmd="${this.mode==='preview'?'design':'help'}">${this.mode==='preview'?'Return to Design':'Editor guide'}</button></div>`;return;}
    if(this.inspector==='layers'){let count=0;const tree=(node,depth=0)=>{if(count++>800||node.matches('[data-pf-runtime],template,script,style'))return '';const children=[...node.children].filter(c=>!c.matches('template,script,style,[data-pf-runtime]'));const label=node.id?'#'+node.id:node.classList.length?'.'+node.classList[0]:node.children.length?'':node.textContent.trim().slice(0,35);return `<div class="layer-row ${node===el?'active':''}" role="button" tabindex="0" draggable="${node!==this.editor.doc.body}" data-node-path="${safeJSON(this.editor.nodePath(node))}" style="padding-left:${8+Math.min(depth,12)*11}px">${icon(children.length?'down':'code')}<span class="layer-tag">${node.tagName.toLowerCase()}</span><span class="layer-text">${escapeHTML(label)}</span></div>`+children.map(c=>tree(c,depth+1)).join('');};root.innerHTML='<p class="panel-description">Select any element. Drag a layer onto the page to move it after the target.</p><div class="layers-tree">'+tree(this.editor.doc.body)+'</div>';return;}
    if(!el?.isConnected){root.innerHTML='<p class="panel-description">Select an element on the page to edit its properties.</p>';return;}
    const computed=this.editor.frame.contentWindow.getComputedStyle(el),r=el.getBoundingClientRect(),tag=el.tagName.toLowerCase(),css=name=>el.style.getPropertyValue(name),placeholder=name=>computed.getPropertyValue(name),val=name=>el.getAttribute('data-pf-'+name)||el.getAttribute(name)||'';const pair=(a,b)=>`<div class="property-pair">${a}${b}</div>`;
    root.innerHTML=`<div class="element-card"><div class="element-identity"><span class="element-tag">${escapeHTML(tag)}</span><div><div class="element-name">${escapeHTML(({h1:'Heading 1',h2:'Heading 2',h3:'Heading 3',p:'Paragraph',img:'Image',a:'Hyperlink',section:'Section',div:'Division',body:'Page body',table:'Table',td:'Table cell',th:'Header cell'})[tag]||cap(tag))}</div><div class="element-subtitle">${escapeHTML(el.textContent.trim().slice(0,80)||el.getAttribute('alt')||tag+' element')}</div></div></div><div class="element-actions"><button data-cmd="duplicate" title="Duplicate element">${icon('copy')} Duplicate</button><button data-cmd="move-up" title="Move up">${icon('up')}</button><button data-cmd="move-down" title="Move down">${icon('down')}</button><button class="action-danger" data-cmd="delete-element" title="Delete element">${icon('trash')}</button></div></div>
    <div class="property-section"><div class="property-heading">ELEMENT <span>HTML5</span></div>${attrInput('ID','id',el.id,'element-id')}${attrInput('Class','class',el.getAttribute('class')||'','class-name')}${tag==='a'?attrInput('Link','href',val('href'),'https://…'):''}${tag==='img'?attrInput('Source','src',val('src'))+attrInput('Alt text','alt',el.getAttribute('alt')||'','Describe the image'):''}${['input','textarea','select','button'].includes(tag)?attrInput('Name','name',val('name'))+attrInput('Type','type',val('type')):''}${attrInput('Title','title',val('title'),'Tooltip (optional)')}</div>
    <div class="property-section"><div class="property-heading">LAYOUT <span>CSS</span></div>${pair(cssInput('W','width',css('width'),Math.round(r.width)+'px'),cssInput('H','height',css('height'),Math.round(r.height)+'px'))}<label class="property-row"><span>Display</span><select data-css="display" aria-label="Display"><option value="">${placeholder('display')} (inherited)</option>${['block','inline','inline-block','flex','grid','none'].map(v=>`<option value="${v}" ${css('display')===v?'selected':''}>${v}</option>`).join('')}</select></label>${cssInput('Padding','padding',css('padding'),placeholder('padding'))}${cssInput('Margin','margin',css('margin'),placeholder('margin'))}${cssInput('Gap','gap',css('gap'),placeholder('gap'))}</div>
    <div class="property-section"><div class="property-heading">TYPOGRAPHY</div>${cssInput('Font','font-family',css('font-family'),placeholder('font-family'))}${pair(cssInput('Size','font-size',css('font-size'),placeholder('font-size')),cssInput('Wght','font-weight',css('font-weight'),placeholder('font-weight')))}${cssInput('Height','line-height',css('line-height'),placeholder('line-height'))}${cssInput('Color','color',css('color'),placeholder('color'))}</div>
    <div class="property-section"><div class="property-heading">APPEARANCE</div>${cssInput('Fill','background',css('background'),placeholder('background-color'))}${cssInput('Border','border',css('border'),'none')}${cssInput('Radius','border-radius',css('border-radius'),placeholder('border-radius'))}<div class="property-heading" style="margin-bottom:6px">BOX MODEL</div><div class="box-model"><span class="box-label">margin</span><span class="box-top">${parseInt(computed.marginTop)||0}</span><span class="box-bottom">${parseInt(computed.marginBottom)||0}</span><span class="box-left">${parseInt(computed.marginLeft)||0}</span><span class="box-right">${parseInt(computed.marginRight)||0}</span><div class="padding-box"><span class="box-label">padding</span><span class="box-top">${parseInt(computed.paddingTop)||0}</span><span class="box-bottom">${parseInt(computed.paddingBottom)||0}</span><span class="box-left">${parseInt(computed.paddingLeft)||0}</span><span class="box-right">${parseInt(computed.paddingRight)||0}</span><div class="content-box">${Math.round(r.width)} × ${Math.round(r.height)}</div></div></div></div>`;
  }
  renderSource(force=false){const file=this.model.active,input=$('#source-input');if(!file)return;if(file.kind==='data'){input.value='Binary asset: '+file.path+'\n\n'+humanBytes(bytesFromFile(file).length)+' · '+file.mime+'\n\nUse File → Export current file to download this asset.\nInsert it into an HTML page using Insert → Image.';input.readOnly=true;}else{input.readOnly=false;if(force||document.activeElement!==input){const start=input.selectionStart,end=input.selectionEnd,scroll=input.scrollTop;input.value=file.content;input.setSelectionRange(Math.min(start,input.value.length),Math.min(end,input.value.length));input.scrollTop=scroll;}}$('#source-label').textContent=extension(file.path).toUpperCase()+' source';this.renderHighlight();this.sourcePosition();}
  renderHighlight(){const text=$('#source-input').value;const ext=extension(this.model.active.path);let html='';if(text.length>350000){html=escapeHTML(text);}else{const rx=isHTML(this.model.active.path)||ext==='svg'?/<!--[\s\S]*?-->|<![^>]*>|<\/?[a-zA-Z][^>]*>/g:/\/\*[\s\S]*?\*\/|\/\/[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\b(?:const|let|var|function|return|if|else|for|while|class|new|import|export|async|await|true|false|null)\b/g;let last=0;for(const match of text.matchAll(rx)){html+=escapeHTML(text.slice(last,match.index));const token=match[0];let cls=token.startsWith('<!--')||token.startsWith('/*')||token.startsWith('//')?'syntax-comment':token.startsWith('<')?'syntax-tag':/^["']/.test(token)?'syntax-string':'syntax-keyword';html+=`<span class="${cls}">${escapeHTML(token)}</span>`;last=match.index+token.length;}html+=escapeHTML(text.slice(last));}$('#syntax-highlight').innerHTML=html+'\n';$('#line-numbers').textContent=Array.from({length:text.split('\n').length+1},(_,i)=>i+1).join('\n');$('#syntax-highlight').scrollTop=$('#source-input').scrollTop;$('#syntax-highlight').scrollLeft=$('#source-input').scrollLeft;$('#line-numbers').scrollTop=$('#source-input').scrollTop;}
  commitSource(refresh=true){clearTimeout(this.sourceTimer);this.sourceTimer=0;const file=this.model.active;if(!file||file.kind==='data')return;const value=$('#source-input').value;if(value===file.content)return;this.model.update(file.path,value,'Source edit');if(refresh&&this.mode==='split'&&isHTML(file.path))this.editor.load(file.path);if(refresh&&this.mode==='preview')this.renderPreview();}
  sourcePosition(){const t=$('#source-input'),before=t.value.slice(0,t.selectionStart),line=before.split('\n').length,col=before.length-before.lastIndexOf('\n');$('#source-position').textContent=`Ln ${line}, Col ${col}`;}
  async history(direction){this.flush();const item=this.model.restore(direction);if(!item)return;this.renderSource(true);if(isHTML(this.model.active.path)){if(this.mode==='preview')this.renderPreview();else if(this.mode!=='code')await this.editor.load(this.model.active.path,item.bookmark);}this.renderHeader();this.renderSaveState();}
  renderPreview(){this.flush();$('#preview-frame').srcdoc=this.runtime.prepare(this.model.active.path,{design:false,channel:this.channelId});this.renderModeState();this.layout();}
  scheduleSave(){if(!this.settings.autosave||this.autosavePaused||this.store.backend==='memory')return;clearTimeout(this.autosaveTimer);this.autosaveTimer=setTimeout(()=>this.saveNow(false),650);}
  async saveNow(showToast=false){this.flush();clearTimeout(this.autosaveTimer);if(showToast)this.autosavePaused=false;const revision=this.model.revision,identity=this.model.data,snapshot=this.model.snapshot();$('#local-indicator').innerHTML=icon('clock')+' Saving…';this.saveChain=this.saveChain.catch(()=>{}).then(()=>this.store.write(snapshot));try{await this.saveChain;if(this.model.data===identity)this.model.savedRevision=revision;this.broadcast?.postMessage({source:this.channelId,type:'saved'});this.renderSaveState();if(showToast)this.toast('Project saved in this browser · '+this.store.backend);}catch(error){this.renderSaveState();if(showToast||!this.storageWarning){this.toast(error.message||'Save failed. Export your project to keep your work.',true);this.storageWarning=true;}}}
  renderSaveState(){if(this.store.backend==='memory'){$('#local-indicator').innerHTML=icon('export')+' Export to save';$('#status-message').innerHTML=icon('warning')+' Memory only · export your project to keep your work';return;}const saved=this.model.revision===this.model.savedRevision;const text=this.autosavePaused?'Autosave paused':saved?'Saved locally':'Unsaved changes';$('#local-indicator').innerHTML=icon(saved?'check':'clock')+' '+text;$('#status-message').innerHTML=icon(saved?'check':'clock')+' '+(this.autosavePaused?'Autosave paused · another tab saved':saved?'Ready · saved locally':this.settings.autosave?'Editing · autosave pending':'Editing · press Ctrl+S to save');}
  touch(label){this.model.revision++;this.model.emit('metadata',{label});}
  toast(message,error=false){const element=document.createElement('div');element.className='toast'+(error?' error':'');element.innerHTML=icon(error?'warning':'check')+`<span>${escapeHTML(message)}</span>`;$('#toast-region').append(element);setTimeout(()=>element.remove(),error?7500:3800);}
  modal(title,body,{ok='OK',cancel='Cancel',width=470}={}){const dialog=$('#modal');if(dialog.open)dialog.close('cancel');dialog.style.width=width+'px';dialog.innerHTML=`<form method="dialog"><div class="modal-header"><h2>${escapeHTML(title)}</h2><button value="cancel" formnovalidate aria-label="Close dialog">×</button></div><div class="modal-body">${body}</div><div class="modal-footer">${cancel?`<button value="cancel" formnovalidate>${escapeHTML(cancel)}</button>`:''}<button value="ok" class="primary-button">${escapeHTML(ok)}</button></div></form>`;dialog.returnValue='';return new Promise(resolve=>{dialog.addEventListener('close',()=>{const form=dialog.querySelector('form');resolve(dialog.returnValue==='ok'?Object.fromEntries(new FormData(form)):null);},{once:true});dialog.showModal();requestAnimationFrame(()=>{const field=dialog.querySelector('input:not([type=checkbox]),textarea,select');field?.focus();if(field?.tagName==='INPUT'&&field.type==='text')field.select();});});}
  async newFile(){const result=await this.modal('New page or file',`<p>Create a file in your website. Use folders in the name, such as <code>pages/services.html</code>.</p>${formField('File name','path','new-page.html','text','required')}${formField('Page title','title','A new page')}<label class="field">Template<select name="template"><option value="blank">Blank page</option><option value="studio">Studio page · shared stylesheet</option><option value="landing">Landing page</option><option value="empty">Empty source file</option></select></label>`,{ok:'Create file'});if(!result)return;const path=normalizePath(result.path);let content='';if(isHTML(path)&&result.template!=='empty'){const title=result.title||'Untitled';if(result.template==='studio'){content=htmlDocument(escapeHTML(title),`<header><a class="brand" href="${relativePath(path,'index.html')}">Your studio</a><nav><a href="${relativePath(path,'index.html')}">Home</a></nav></header><main><section class="section"><h1>${escapeHTML(title)}</h1><p>Tell your story. Make this page your own.</p></section></main>`);content=content.replace('href="styles/site.css"',`href="${relativePath(path,'styles/site.css')}"`).replace('src="scripts/site.js"',`src="${relativePath(path,'scripts/site.js')}"`);}else if(result.template==='landing'){content=blankPage(title).replace('<p>Start writing your next great website.</p>',`<p style="font-size:22px;color:#778">Your next big idea deserves a great first impression.</p><a href="#features" style="display:inline-block;padding:14px 25px;background:#285ba7;color:white;text-decoration:none;border-radius:6px">Get started →</a><section id="features" style="padding:60px 0;display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:25px"><article><h2>Simple</h2><p>Designed for the things that matter.</p></article><article><h2>Powerful</h2><p>Everything you need to get started.</p></article><article><h2>Yours</h2><p>Make it your own.</p></article></section>`);}else content=blankPage(title);}else if(extension(path)==='css')content='/* Your stylesheet */\nbody {\n  margin: 0;\n  font-family: system-ui, sans-serif;\n}\n';else if(extension(path)==='js')content='// Your JavaScript\n';else if(extension(path)==='json')content='{}\n';this.model.add(path,content);await this.openFile(path);if(isHTML(path))await this.setMode('design');this.toast('Created '+path);}
  async linkDialog(){await this.ensureDesign();const selected=this.editor.selected?.closest('a'),text=this.editor.range?.toString()||selected?.textContent||'';const pages=this.model.files.filter(f=>isHTML(f.path)).map(f=>`<option value="${escapeHTML(relativePath(this.model.active.path,f.path))}"></option>`).join('');const result=await this.modal('Insert hyperlink',`${formField('Text to display','text',text)}${formField('Address or page','href',selected?.getAttribute('href')||'','text','required list="page-addresses" placeholder="https://example.com or about.html"')}<datalist id="page-addresses">${pages}</datalist><label class="checkbox-label"><input type="checkbox" name="newtab" ${selected?.target==='_blank'?'checked':''}> Open in a new tab</label><p class="modal-note">Local website links resolve inside Preview. External links stay sandboxed while editing.</p>`,{ok:selected?'Update link':'Insert link'});if(result)this.editor.link(result.href,result.text,!!result.newtab);}
  async imageDialog(){await this.ensureDesign();const selected=this.editor.selected?.tagName==='IMG'?this.editor.selected:null,images=this.model.files.filter(f=>/\.(svg|png|jpe?g|webp|gif|ico)$/i.test(f.path));const result=await this.modal(selected?'Image properties':'Insert image',`${formField('Image path or URL','src',selected?.getAttribute('data-pf-src')||selected?.getAttribute('src')||relativePath(this.model.active.path,images[0]?.path||'assets/image.png'),'text','required list="project-images"')}<datalist id="project-images">${images.map(f=>`<option value="${escapeHTML(relativePath(this.model.active.path,f.path))}"></option>`).join('')}</datalist><button type="button" class="secondary-button" data-cmd="upload-image">${icon('import')} Import an image from your computer</button><div style="height:14px"></div>${formField('Alternative text','alt',selected?.getAttribute('alt')||'','text','placeholder="Describe the image for screen readers"')}<div class="field-grid">${formField('Width (CSS)','width',selected?.style.width||'100%')}${formField('Height (CSS)','height',selected?.style.height||'auto')}</div>`,{ok:selected?'Apply changes':'Insert image'});if(!result)return;if(/^\s*(javascript|vbscript|data:text\/html):/i.test(result.src))throw new Error('Unsupported image URL.');for(const prop of ['width','height'])if(result[prop]&&!CSS.supports(prop,result[prop]))throw new Error('Invalid '+prop+' CSS value.');if(selected){this.editor.transaction('Image properties',()=>{selected.setAttribute('alt',result.alt);selected.setAttribute('src',result.src);selected.removeAttribute('data-pf-src');selected.style.width=result.width;selected.style.height=result.height;this.editor.resolveInserted(selected);});}else this.editor.insertHTML(`<figure style="margin:24px 0"><img src="${escapeHTML(result.src)}" alt="${escapeHTML(result.alt)}" style="width:${escapeHTML(result.width||'100%')};height:${escapeHTML(result.height||'auto')};max-width:100%"></figure>`,'Insert image');}
  async tableDialog(){await this.ensureDesign();const result=await this.modal('Insert table',`<div class="field-grid">${formField('Rows','rows','3','number','required min="1" max="50"')}${formField('Columns','columns','3','number','required min="1" max="20"')}</div><label class="checkbox-label"><input type="checkbox" name="header" checked> First row contains column headings</label><p class="modal-note">Use the Table menu to add or remove rows and columns after insertion. Select a cell and press Tab to move between cells.</p>`,{ok:'Insert table'});if(!result)return;const rows=Math.min(50,Math.max(1,Number(result.rows)||1)),cols=Math.min(20,Math.max(1,Number(result.columns)||1));const row=(tag,index)=>'<tr>'+Array.from({length:cols},(_,i)=>`<${tag}${tag==='th'?' scope="col"':''}>${tag==='th'?'Heading '+(i+1):'Cell '+(index+1)+', '+(i+1)}</${tag}>`).join('')+'</tr>';this.editor.insertHTML(`<table style="width:100%;border-collapse:collapse;margin:24px 0">${result.header?'<thead>'+row('th',0)+'</thead>':''}<tbody>${Array.from({length:rows-(result.header?1:0)},(_,i)=>row('td',i)).join('')}</tbody></table>`,'Insert table');}
  async htmlDialog(){await this.ensureDesign();const result=await this.modal('Insert HTML',`<p>Insert an HTML fragment after the selected block. Scripts and active embeds are removed from pasted fragments; use Code view for authored scripts.</p><label class="field">HTML fragment<textarea name="html" spellcheck="false" required>&lt;section style="padding:32px"&gt;\n  &lt;h2&gt;Make something great&lt;/h2&gt;\n  &lt;p&gt;Your content goes here.&lt;/p&gt;\n&lt;/section&gt;</textarea></label>`,{ok:'Insert HTML',width:610});if(result)this.editor.insertHTML(this.editor.sanitize(result.html),'Insert HTML');}
  async insertComponent(id){const c=componentLibrary.find(c=>c.id===id);if(!c)return;await this.ensureDesign();let html=c.html;html=html.replace(/(href|src)="((?:assets\/|contact\.html)[^"]*)"/g,(match,attr,path)=>`${attr}="${escapeHTML(relativePath(this.model.active.path,path))}"`);this.editor.insertHTML(html,'Insert '+c.name);this.toast(c.name+' inserted');}
  async copy(cut=false){if(this.mode==='code'){const t=$('#source-input'),text=t.value.slice(t.selectionStart,t.selectionEnd);await navigator.clipboard.writeText(text);if(cut){t.setRangeText('',t.selectionStart,t.selectionEnd,'end');t.dispatchEvent(new Event('input'));}return;}await this.ensureDesign();const range=this.editor.restoreRange(),text=range&&!range.collapsed?range.toString():this.editor.selected?.outerHTML||'';try{await navigator.clipboard.writeText(text);}catch{await this.modal('Copy selection',`<p>Clipboard access was not available. Copy the content below.</p><label class="field">Selection<textarea name="text">${escapeHTML(text)}</textarea></label>`,{ok:'Done',cancel:null,width:600});return;}if(cut){if(range&&!range.collapsed)this.editor.transaction('Cut',()=>range.deleteContents());else this.editor.remove();}this.toast(cut?'Selection cut':'Selection copied');}
  async paste(){await this.ensureDesign();try{const text=await navigator.clipboard.readText();this.editor.insertText(text);}catch{const result=await this.modal('Paste text',`<p>Paste from your clipboard into this field.</p><label class="field">Text<textarea name="text" required></textarea></label>`,{ok:'Insert text'});if(result)this.editor.insertText(result.text);}}
  async renameFile(path){this.flush();const result=await this.modal('Rename file',`${formField('New path','path',path,'text','required')}<p class="modal-note">Relative href, src, poster and stylesheet references in HTML files are updated. CSS url() references are updated too. JavaScript strings are not refactored.</p>`,{ok:'Rename'});if(!result)return;const next=normalizePath(result.path);if(next===path)return;if(this.model.get(next))throw new Error('A file already exists at that path.');const before=this.model.files.map(f=>({...f}));this.model.rename(path,next);this.openTabs=this.openTabs.map(p=>p===path?next:p);
    for(const old of before){const currentPath=old.path===path?next:old.path;let content=old.content;if(old.kind==='data')continue;
      if(isHTML(old.path)){const doc=new DOMParser().parseFromString(content,'text/html');let changed=false;for(const el of doc.querySelectorAll('[href],[src],[poster]'))for(const attr of ['href','src','poster'])if(el.hasAttribute(attr)){const raw=el.getAttribute(attr),resolved=resolvePath(old.path,raw);if(resolved===path||old.path===path&&resolved){const target=resolved===path?next:resolved,suffix=raw.match(/[?#].*$/)?.[0]||'';el.setAttribute(attr,relativePath(currentPath,target)+suffix);changed=true;}}if(changed)content='<!DOCTYPE html>\n'+doc.documentElement.outerHTML;
      }else if(extension(old.path)==='css'){content=content.replace(/url\(\s*(["']?)([^)'"\s]+)\1\s*\)/gi,(match,quote,url)=>{const resolved=resolvePath(old.path,url);return resolved===path||old.path===path&&resolved?`url("${relativePath(currentPath,resolved===path?next:resolved)}${url.match(/[?#].*$/)?.[0]||''}")`:match;});}
      if(content!==this.model.get(currentPath).content)this.model.update(currentPath,content,'Refactor file references');
    }
    await this.openFile(this.model.active.path);this.toast('Renamed to '+next);}
  async deleteFile(path){const result=await this.modal('Delete file',`<p>Delete <strong>${escapeHTML(path)}</strong> from this project?</p><p class="modal-note">This removes the file and its undo history. Links from other pages are not removed. Export a backup before deleting files you may need later.</p>`,{ok:'Delete file'});if(!result)return;this.flush();this.model.remove(path);this.openTabs=this.openTabs.filter(p=>p!==path);await this.openFile(this.model.active.path);this.toast('Deleted '+path);}
  async pageProperties(){if(!isHTML(this.model.active.path))throw new Error('Page properties are available for HTML files.');this.flush();const doc=new DOMParser().parseFromString(this.model.active.content,'text/html');const result=await this.modal('Page properties',`${formField('Page title','title',doc.title,'text','required')}${formField('Description','description',doc.querySelector('meta[name="description"]')?.content||'')}${formField('Language','language',doc.documentElement.lang||'en')}${formField('Project name','project',this.model.data.name)}<p class="modal-note">The title appears in the browser tab. A clear description helps people understand your page.</p>`,{ok:'Apply changes'});if(!result)return;doc.title=result.title;doc.documentElement.lang=result.language||'en';let meta=doc.querySelector('meta[name="description"]');if(!meta){meta=doc.createElement('meta');meta.name='description';doc.head.append(meta);}meta.content=result.description;this.model.update(this.model.active.path,'<!DOCTYPE html>\n'+doc.documentElement.outerHTML,'Page properties');if(this.model.data.name!==result.project){this.model.data.name=result.project||'Untitled website';this.touch('Rename project');}await this.openFile(this.model.active.path);this.toast('Page properties updated');}
  async importSingle(file,prefix=''){if(file.size>LIMITS.fileBytes)throw new Error('File exceeds the 12 MB limit: '+file.name);let path=normalizePath(prefix+(file.webkitRelativePath||file.name)),name=path;let i=2;while(this.model.get(path)){const dot=name.lastIndexOf('.');path=dot>0?name.slice(0,dot)+'-'+i+name.slice(dot):name+'-'+i;i++;}const bytes=new Uint8Array(await file.arrayBuffer());const kind=isTextFile(path)?'text':'data',content=kind==='text'?new TextDecoder().decode(bytes):dataURI(bytes,mimeType(path));return this.model.add(path,content,kind);}
  async importFiles(files){if(!files.length)return;try{this.flush();if(files.length===1&&/\.(pageforge|json)$/i.test(files[0].name)){if(files[0].size>LIMITS.projectBytes)throw new Error('Project exceeds 48 MB.');const text=await files[0].text();let data;try{data=JSON.parse(text);}catch{}if(data?.version&&data?.files){const valid=validateProject(data);const confirm=await this.modal('Open project',`<p>Open <strong>${escapeHTML(valid.name)}</strong> with ${valid.files.length} files?</p><p class="modal-note">This replaces the current workspace. Export your current project first to preserve it separately.</p>`,{ok:'Open project'});if(confirm)await this.replaceProject(valid);return;}}
      if(files.length===1&&/\.zip$/i.test(files[0].name)){const entries=await readZip(await files[0].arrayBuffer());if(!entries.length)throw new Error('The ZIP contains no files.');const valid=validateProject({version:PROJECT_VERSION,name:files[0].name.replace(/\.zip$/i,''),active:'index.html',files:entries.map(f=>({path:f.path,kind:isTextFile(f.path)?'text':'data',content:isTextFile(f.path)?new TextDecoder().decode(f.bytes):dataURI(f.bytes,mimeType(f.path))})),tasks:[]});const confirm=await this.modal('Import website ZIP',`<p>Open <strong>${escapeHTML(valid.name)}</strong> with ${valid.files.length} files?</p><p class="modal-note">The archive is unpacked locally. The current workspace will be replaced.</p>`,{ok:'Open website'});if(confirm)await this.replaceProject(valid);return;}
      if(this.model.files.length+files.length>LIMITS.files)throw new Error('Import exceeds the 512-file project limit.');if(files.reduce((n,f)=>n+f.size,0)>LIMITS.projectBytes)throw new Error('Import exceeds 48 MB.');const added=[];for(const f of files)added.push(await this.importSingle(f));const html=added.find(f=>isHTML(f.path));if(html)await this.openFile(html.path);else if(added.length===1&&!added[0].mime.startsWith('image/'))await this.openFile(added[0].path);this.renderTree();this.toast(`Imported ${added.length} file${added.length===1?'':'s'}`);
    }catch(error){this.toast(error.message,true);}}
  async replaceProject(data){this.editor.dispose();this.sourceTimer=0;this.model.load(data);this.model.revision++;this.openTabs=[this.model.active.path];this.runtime.cache.clear();this.collapsed.clear();$('#file-filter').value='';this.mode=isHTML(this.model.active.path)?'design':'code';this.view='page';await this.openFile(this.model.active.path);await this.saveNow(false);this.toast('Opened '+this.model.data.name);}
  exportProject(){this.flush();downloadBlob(new Blob([JSON.stringify(this.model.snapshot(),null,2)],{type:'application/json'}),this.slug()+'.pageforge');this.toast('Project backup exported with all pages and assets');}
  exportFile(){this.flush();const file=this.model.active;downloadBlob(new Blob([bytesFromFile(file)],{type:file.mime||mimeType(file.path)}),file.path.split('/').pop());this.toast('Exported '+file.path);}
  exportSite(){this.flush();const entries=this.model.files.map(f=>({path:f.path,bytes:bytesFromFile(f)}));downloadBlob(createZip(entries),this.slug()+'-website.zip');this.toast('Website ZIP exported · standard HTML, CSS, JavaScript, and assets');}
  slug(){return this.model.data.name.toLowerCase().replace(/[^a-z\d]+/g,'-').replace(/^-|-$/g,'')||'website';}
  async publishDialog(){const result=await this.modal('Publish website',`<div class="brand-about"><span class="app-logo">${icon('globe')}</span><div><strong style="font-size:20px">Ready for the web.</strong><small>${this.model.files.length} files · standard, portable website</small></div></div><p>Export a deployment-ready ZIP containing your HTML, CSS, JavaScript, and assets. Upload its contents to GitHub Pages, Netlify, Cloudflare Pages, or any static web host.</p><p class="modal-note"><strong>No hosting account is connected to this editor.</strong> This action downloads your website; it does not upload or publish it online. Custom form delivery and server features require your own endpoint.</p><label class="checkbox-label" style="margin-top:15px"><input type="checkbox" name="backup" checked> Also download an editable PageForge project backup</label>`,{ok:'Export website',cancel:'Not now',width:510});if(result){this.exportSite();if(result.backup)setTimeout(()=>this.exportProject(),300);}}
  async showFind(){if(this.mode!=='code'&&this.mode!=='split')await this.setMode('code');$('#find-bar').hidden=false;$('#find-input').focus();$('#find-input').select();this.updateFindCount();}
  updateFindCount(){const q=$('#find-input').value,text=$('#source-input').value;let count=0,p=0;if(q)while((p=text.toLowerCase().indexOf(q.toLowerCase(),p))!==-1){count++;p+=Math.max(1,q.length);}$('#find-count').textContent=q?count+' found':'';}
  findNext(){const q=$('#find-input').value;if(!q)return;const t=$('#source-input'),start=t.selectionEnd;let at=t.value.toLowerCase().indexOf(q.toLowerCase(),start);if(at<0)at=t.value.toLowerCase().indexOf(q.toLowerCase());if(at<0){this.toast('No matches found');return;}t.focus();t.setSelectionRange(at,at+q.length);const line=t.value.slice(0,at).split('\n').length;t.scrollTop=Math.max(0,(line-4)*21);t.dispatchEvent(new Event('scroll'));this.sourcePosition();}
  replace(all=false){const q=$('#find-input').value,replace=$('#replace-input').value,t=$('#source-input');if(!q||t.readOnly)return;let count=0;if(all){const escaped=q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');t.value=t.value.replace(new RegExp(escaped,'gi'),()=>{count++;return replace;});}else{if(t.value.slice(t.selectionStart,t.selectionEnd).toLowerCase()!==q.toLowerCase())this.findNext();if(t.value.slice(t.selectionStart,t.selectionEnd).toLowerCase()===q.toLowerCase()){t.setRangeText(replace,t.selectionStart,t.selectionEnd,'end');count=1;}}if(count){this.commitSource();this.renderHighlight();this.updateFindCount();this.toast(`Replaced ${count} occurrence${count===1?'':'s'}`);}}
  formatCode(){this.flush();if(!isHTML(this.model.active.path))throw new Error('The built-in formatter handles HTML files. CSS and JavaScript source is preserved as authored.');const raw=this.model.active.content,protectedBlocks=[];let content=raw.replace(/<(pre|script|style|textarea)\b[^>]*>[\s\S]*?<\/\1>/gi,match=>{const key=`PAGEFORGE_PROTECTED_${protectedBlocks.length}`;protectedBlocks.push(match);return key;});content=content.replace(/>\s*</g,'>\n<').split('\n').map(l=>l.trim()).filter(Boolean);let level=0;const formatted=content.map(line=>{if(/^<\//.test(line))level=Math.max(0,level-1);const out='  '.repeat(Math.min(level,20))+line;if(/^<(html|head|body|main|section|article|header|footer|nav|div|ul|ol|li|table|thead|tbody|tr|form)\b/i.test(line)&&!/<\/[^>]+>\s*$/.test(line))level++;return out;}).join('\n').replace(/PAGEFORGE_PROTECTED_(\d+)/g,(_,i)=>protectedBlocks[Number(i)]);this.model.update(this.model.active.path,formatted+'\n','Format HTML');this.renderSource(true);if(this.mode==='split')this.editor.load(this.model.active.path);this.toast('HTML source formatted');}
  analyze(){this.flush();const issues=[],links=[],pages=[];let total=0;for(const file of this.model.files){total+=bytesFromFile(file).byteLength;if(!isHTML(file.path))continue;const doc=new DOMParser().parseFromString(file.content,'text/html');pages.push({path:file.path,title:doc.title||file.path});if(!doc.title.trim())issues.push({severity:'warning',path:file.path,detail:'The page is missing a descriptive title.'});if(!doc.documentElement.lang)issues.push({severity:'warning',path:file.path,detail:'The html element has no language attribute.'});if(!doc.querySelector('meta[name="description"]')?.content)issues.push({severity:'warning',path:file.path,detail:'The page has no meta description.'});const ids=new Set();for(const el of doc.querySelectorAll('[id]')){if(ids.has(el.id))issues.push({severity:'warning',path:file.path,detail:'Duplicate id: '+el.id});ids.add(el.id);}for(const img of doc.querySelectorAll('img'))if(!img.hasAttribute('alt'))issues.push({severity:'warning',path:file.path,detail:'An image has no alt attribute.'});for(const form of doc.querySelectorAll('form'))if(!form.getAttribute('action'))issues.push({severity:'warning',path:file.path,detail:'Form has no delivery endpoint; review its JavaScript handler.'});for(const el of doc.querySelectorAll('a[href],link[href],img[src],script[src],source[src]')){const raw=el.getAttribute('href')||el.getAttribute('src')||'',target=resolvePath(file.path,raw);let broken=false;if(target&&!this.model.get(target)){broken=true;issues.push({severity:'error',path:file.path,detail:'Missing local resource: '+raw});}else if(raw.startsWith('#')&&raw.length>1){try{const id=decodeURIComponent(raw.slice(1));if(!doc.getElementById(id)){broken=true;issues.push({severity:'warning',path:file.path,detail:'Anchor target not found: '+raw});}}catch{}}if(el.tagName==='A')links.push({from:file.path,raw,target,broken,label:el.textContent.trim()||raw,external:!target&&!raw.startsWith('#')});}}
    return {issues,links,pages,total,broken:issues.filter(i=>i.severity==='error').length};}
  renderSiteView(){const root=$('#site-view');if(this.view==='page'){root.hidden=true;return;}const report=this.analyze(),title=({folders:'Website folders',reports:'Website reports',navigation:'Site navigation',hyperlinks:'Hyperlinks',tasks:'Website tasks',website:'Your website'})[this.view],subtitle=({folders:'All the pieces of your website, in one place.',reports:'A local scan of links, metadata, accessibility hints, and forms.',navigation:'A page inventory rooted at the homepage. Inspect actual links in Hyperlinks view.',hyperlinks:'Inspect authored links and their local destinations. External URLs are not fetched.',tasks:'A small checklist. A better website.',website:'A familiar workspace. A whole new set of possibilities.'})[this.view];const header=`<div class="site-heading"><div><h1>${title}</h1><p>${subtitle}</p></div><button class="secondary-button" data-cmd="${this.view==='folders'?'import':'refresh'}">${icon(this.view==='folders'?'import':'refresh')} ${this.view==='folders'?'Import files':'Refresh'}</button></div>`;
    const stats=`<div class="stats-grid"><div class="stat-card"><strong>${this.model.files.length}</strong><span>Project files</span></div><div class="stat-card"><strong>${report.pages.length}</strong><span>HTML pages</span></div><div class="stat-card"><strong>${report.broken}</strong><span>Broken resources</span></div><div class="stat-card"><strong>${humanBytes(report.total)}</strong><span>Total website size</span></div></div>`;
    let content='';
    if(this.view==='folders'){content=stats+`<table class="data-table"><thead><tr><th>Name</th><th>Type</th><th>Size</th><th>Modified</th><th></th></tr></thead><tbody>${this.model.files.toSorted((a,b)=>a.path.localeCompare(b.path)).map(f=>`<tr><td><button class="file-cell" data-file="${escapeHTML(f.path)}">${icon(fileIcon(f.path))}${escapeHTML(f.path)}</button></td><td>${extension(f.path).toUpperCase()}</td><td>${humanBytes(bytesFromFile(f).length)}</td><td>${new Date(f.modified).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</td><td><button class="row-button" data-cmd="rename" data-value="${escapeHTML(f.path)}" title="Rename ${escapeHTML(f.path)}">${icon('rename')}</button><button class="row-button" data-cmd="delete-file" data-value="${escapeHTML(f.path)}" title="Delete ${escapeHTML(f.path)}">${icon('trash')}</button></td></tr>`).join('')}</tbody></table>`;}
    else if(this.view==='reports'){content=stats+`<div class="report-section-title">${report.issues.length?report.issues.length+' items to review':'All checks passed'}</div>`+(report.issues.length?`<table class="data-table"><thead><tr><th>Type</th><th>Page</th><th>Finding</th></tr></thead><tbody>${report.issues.map(i=>`<tr><td><span class="issue-badge ${i.severity==='error'?'error':''}">${icon('warning')}${cap(i.severity)}</span></td><td><button data-issue-path="${escapeHTML(i.path)}">${escapeHTML(i.path)}</button></td><td>${escapeHTML(i.detail)}</td></tr>`).join('')}</tbody></table>`:`<div class="empty-state">${icon('check')}No missing local resources or issues in the checks performed.</div>`)+`<p class="table-note">This is a heuristic local audit, not a complete HTML or WCAG validator. External URLs, network responses, JavaScript behavior, CSS assets, and complex srcset rules are not fully validated.</p>`;}
    else if(this.view==='navigation'){const home=report.pages.find(p=>p.path==='index.html')||report.pages[0];const card=p=>`<button class="sitemap-node" data-file="${escapeHTML(p.path)}">${icon(p.path===home.path?'home':'page')}<span>${escapeHTML(p.path)}</span><small>${escapeHTML(p.title.slice(0,40))}</small></button>`;content=home?`<div class="sitemap"><div class="sitemap-root" style="width:150px">${card(home)}</div><div class="sitemap-children">${report.pages.filter(p=>p!==home).map(card).join('')}</div></div><p class="table-note">${report.pages.length} pages · ${report.links.filter(l=>l.target).length} local hyperlinks. This inventory does not imply a parent-child routing hierarchy.</p>`:'<div class="empty-state">Create an HTML page to build your website navigation.</div>';}
    else if(this.view==='hyperlinks'){content=`<div class="link-groups">${report.pages.map(p=>`<div class="link-group"><h3>${icon('page')} ${escapeHTML(p.path)}</h3>${report.links.filter(l=>l.from===p.path).map(l=>`<button class="${l.broken?'broken':''}" ${l.target&&this.model.get(l.target)?`data-file="${escapeHTML(l.target)}"`:`data-issue-path="${escapeHTML(l.from)}"`} title="${escapeHTML(l.raw)}">${icon(l.broken?'warning':l.external?'external':'link')}<span>${escapeHTML(l.raw)}</span></button>`).join('')||'<p class="panel-description">No links on this page.</p>'}</div>`).join('')}</div>`;}
    else if(this.view==='tasks'){content=`<div class="task-input"><input id="new-task-input" placeholder="Add something to do…" aria-label="New task"><button class="primary-button" data-cmd="add-task">${icon('plus')} Add task</button></div><div class="task-list">${this.model.data.tasks.map(t=>`<label class="task-item ${t.done?'done':''}"><input type="checkbox" data-task-id="${escapeHTML(t.id)}" ${t.done?'checked':''}><span>${escapeHTML(t.text)}</span><button type="button" data-delete-task="${escapeHTML(t.id)}" aria-label="Delete task">${icon('close')}</button></label>`).join('')||'<div class="empty-state">Nothing on the list. Add a task above.</div>'}</div><p class="table-note">${this.model.data.tasks.filter(t=>t.done).length} of ${this.model.data.tasks.length} tasks complete. Tasks are saved in your project backup, not exported to the website.</p>`;}
    else{content=stats+`<div class="website-card"><div><h2>${escapeHTML(this.model.data.name)}</h2><p>Design visually. Fine-tune the source. Preview on any screen. Everything you create is ordinary web code, ready to go anywhere.</p><div class="website-actions"><button class="primary-button" data-file="${escapeHTML(report.pages[0]?.path||this.model.active.path)}">${icon('design')} Edit website</button><button class="secondary-button" data-cmd="publish">${icon('export')} Export site</button></div></div>${this.model.get('assets/pavilion.svg')?`<img src="${this.runtime.asset('assets/pavilion.svg')}" alt="Sample website architecture illustration">`:'<div class="empty-state">'+icon('globe')+'Your next great website.</div>'}</div><div class="report-section-title">A familiar workflow, without the baggage.</div><p class="table-note">Your workspace is stored locally using ${this.store.backend}. Export a .pageforge project for a portable backup, or a website ZIP to publish to a static host. Imported scripts run only in the isolated Preview view.</p>`;}
    root.innerHTML=header+content;if(this.view==='tasks')$('#new-task-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')this.addTask();});}
  addTask(){const input=$('#new-task-input'),text=input?.value.trim();if(!text)return;this.model.data.tasks.push({id:globalThis.crypto?.randomUUID?.()||String(Date.now()),text:text.slice(0,500),done:false});this.touch('Add task');this.renderSiteView();$('#new-task-input')?.focus();}
  openMenu(button){const name=button.dataset.menu,root=$('#dropdown-menu');if(!root.hidden&&root.dataset.openMenu===name){this.closeMenu();return;}this.closeMenu();button.classList.add('open');button.setAttribute('aria-expanded','true');const menus={
    File:[['new','New page or file…','page','Ctrl+N'],['import','Open / import…','folderOpen','Ctrl+O'],null,['save','Save locally','save','Ctrl+S'],['save-project','Save project backup…','save'],['export-file','Export current file…','export'],['export-site','Export website ZIP…','globe'],null,['rename','Rename current file…','rename'],['delete-file','Delete current file…','trash'],null,['page-properties','Page properties…','settings']],
    Edit:[['undo','Undo','undo','Ctrl+Z'],['redo','Redo','redo','Ctrl+Shift+Z'],null,['cut','Cut','cut'],['copy','Copy','copy'],['paste','Paste','paste'],null,['select-all','Select all','section'],['duplicate','Duplicate element','copy','Ctrl+D'],['delete-element','Delete element','trash'],null,['find','Find and replace…','search','Ctrl+F']],
    View:[['design','Design','design'],['split','Split','split'],['code','Code','code'],['preview','Preview','preview','F5'],null,['toggle-folders','Folder list','folder'],['toggle-inspector','Task pane','layers'],['boundaries','Element boundaries','grid'],['grid','Layout grid','grid'],null,['folders','Website folders','folderOpen'],['navigation','Navigation','navigation'],['hyperlinks','Hyperlinks','link']],
    Insert:[['new','New page…','page'],['link','Hyperlink…','link','Ctrl+K'],['image','Image…','image'],['table','Table…','table'],null,['insert-heading','Heading','heading'],['insert-paragraph','Paragraph','paragraph'],['insert-divider','Horizontal line','divider'],['insert-form','Contact form','form'],null,['html','HTML fragment…','code'],['component','Component library','columns']],
    Format:[['bold','Bold','bold','Ctrl+B'],['italic','Italic','italic','Ctrl+I'],['underline','Underline','underline','Ctrl+U'],null,['left','Align left','left'],['center','Center','center'],['right','Align right','right'],['justify','Justify','justify'],null,['ul','Bulleted list','list'],['ol','Numbered list','ordered'],['clear','Clear formatting','clear'],['format-code','Format HTML source','code']],
    Table:[['table','Insert table…','table'],null,['table-row','Insert row after selection','plus'],['table-column','Insert column after selection','columns'],null,['table-delete-row','Delete selected row','trash'],['table-delete-column','Delete selected column','trash']],
    Tools:[['reports','Website reports','reports'],['hyperlinks','Check local hyperlinks','link'],['tasks','Website tasks','tasks'],null,['page-properties','Page properties…','settings'],['settings','Preferences…','settings'],null,['publish','Export for publishing…','globe']],
    Window:[['next-tab','Next document','page'],['close-tab','Close document tab','close'],null,['reset-layout','Reset workspace layout','design']],
    Help:[['help','PageForge guide','help','F1'],['shortcuts','Keyboard shortcuts','terminal'],['about','About PageForge Studio','globe'],null,['reset-demo','Restore sample website…','refresh']]
    };root.innerHTML=(menus[name]||[]).map(item=>item?`<button class="menu-item" role="menuitem" data-cmd="${item[0]}">${icon(item[2])}<span>${item[1]}</span><span class="menu-key">${item[3]||''}</span></button>`:'<div class="menu-divider"></div>').join('');const r=button.getBoundingClientRect();root.style.left=Math.min(r.left,window.innerWidth-260)+'px';root.style.top=r.bottom+'px';root.dataset.openMenu=name;root.hidden=false;}
  closeMenu(){$('#dropdown-menu').hidden=true;$$('[data-menu].open').forEach(b=>{b.classList.remove('open');b.setAttribute('aria-expanded','false');});}
  async settingsDialog(){const result=await this.modal('Preferences',`<label class="field">Workspace appearance<select name="theme"><option value="blue" ${this.settings.theme==='blue'?'selected':''}>Classic Blue</option><option value="silver" ${this.settings.theme==='silver'?'selected':''}>Classic Silver</option></select></label><label class="checkbox-label"><input type="checkbox" name="autosave" ${this.settings.autosave?'checked':''}> Save changes automatically in this browser</label><label class="checkbox-label" style="margin-top:12px"><input type="checkbox" name="spellcheck" ${this.settings.spellcheck?'checked':''}> Native spell checking in Design view</label><p class="modal-note">Storage: ${this.store.backend}<br>Renderer: ${this.renderer.mode}<br>WebGPU overlays use native HTML layout. The renderer falls back automatically when a GPU adapter is unavailable.</p>`,{ok:'Save preferences'});if(!result)return;this.settings={theme:result.theme,autosave:!!result.autosave,spellcheck:!!result.spellcheck};document.body.dataset.theme=this.settings.theme;try{localStorage.setItem('pageforge-settings',JSON.stringify(this.settings));}catch{}if(this.editor.doc)this.editor.doc.body.spellcheck=this.settings.spellcheck;if(this.settings.autosave){this.autosavePaused=false;this.scheduleSave();}this.toast('Preferences saved');}
  async helpDialog(){await this.modal('Welcome to PageForge Studio',`<div class="brand-about"><span class="app-logo">${icon('page')}</span><div><strong>Make the web yours.</strong><small>A familiar website editor, reimagined.</small></div></div><div class="help-step"><strong>1. Start with a page</strong>Open a file in Folder List. Use File → New to create a blank, studio, or landing page. Import ordinary HTML, CSS, JavaScript, images, ZIP websites, or .pageforge backups.</div><div class="help-step"><strong>2. Design directly on the page</strong>Click text and type. Select text to format it. The Properties pane edits CSS and attributes. Insert contains draggable building blocks. Layers selects and reorders the DOM.</div><div class="help-step"><strong>3. Get close to the code</strong>Use Split or Code for source editing. The source editor includes syntax highlighting, line numbers, find/replace, Tab indentation, and HTML formatting.</div><div class="help-step"><strong>4. Check every screen</strong>Switch among desktop, tablet, and phone widths. Preview executes your local JavaScript in a sandbox. Internal page links navigate your project.</div><div class="help-step"><strong>5. Save it. Ship it.</strong>Changes save in this browser. File → Save project backup downloads an editable backup. Publish website exports standard files in a ZIP for your preferred host.</div><p class="modal-note">Design view normalizes HTML through the browser’s parser. It is not a byte-preserving source editor. Scripts are disabled in Design. Preview cannot access your editor’s storage, issue fetch requests, or submit forms to a server.</p>`,{ok:'Start creating',cancel:null,width:580});}
  async shortcutsDialog(){await this.modal('Keyboard shortcuts',`<table class="keyboard-table">${[['Save project locally','Ctrl / ⌘ + S'],['New file','Ctrl / ⌘ + N'],['Import files','Ctrl / ⌘ + O'],['Undo','Ctrl / ⌘ + Z'],['Redo','Ctrl / ⌘ + Shift + Z'],['Bold / italic / underline','Ctrl / ⌘ + B / I / U'],['Insert hyperlink','Ctrl / ⌘ + K'],['Find and replace','Ctrl / ⌘ + F'],['Toggle preview','Ctrl / ⌘ + Enter'],['Preview','F5'],['Select parent element','Esc (in Design)'],['Next table cell','Tab (in table)'],['Indent source line','Tab (in Code)'],['Open linked project page','Ctrl / ⌘ + click (in Design)']].map(([a,b])=>`<tr><td>${a}</td><td><span class="shortcut">${b}</span></td></tr>`).join('')}</table>`,{ok:'Done',cancel:null,width:590});}
  async aboutDialog(){await this.modal('About PageForge Studio',`<div class="brand-about"><span class="app-logo">${icon('page')}</span><div><strong>PageForge Studio</strong><small>Version ${APP_VERSION} · independent implementation</small></div></div><p>A FrontPage-inspired, local-first visual website editor built with plain HTML, CSS, and JavaScript.</p><p><strong>Rendering:</strong> Native browser DOM, CSS layout, typography, selection, and input. WebGPU renders editor overlays using instanced WGSL rectangles, with a Canvas 2D fallback.</p><p><strong>Current renderer:</strong> ${this.renderer.mode}<br><strong>Storage:</strong> ${this.store.backend}<br><strong>Runtime dependencies:</strong> None</p><p class="modal-note">This project is not affiliated with Microsoft. It does not implement FrontPage Server Extensions, ASP/database wizards, collaborative editing, or FTP publishing. It exports ordinary modern static websites.</p>`,{ok:'Done',cancel:null,width:520});}
  async resetDemo(){const result=await this.modal('Restore sample website',`<p>Replace the current workspace with the Monograph Studio sample?</p><p class="modal-note">This replaces the current project. Export a .pageforge backup first to keep your work.</p>`,{ok:'Restore sample'});if(result)await this.replaceProject(starterProject());}
}
new PageForgeApp().init().catch(error=>{console.error(error);const panel=document.createElement('div');panel.style.cssText='position:fixed;inset:20%;z-index:999;background:white;padding:32px;border:1px solid #b77;font:14px/1.6 system-ui';panel.innerHTML='<h1>PageForge could not start</h1><p>'+escapeHTML(error.message)+'</p><p>Try a recent browser or serve this file from localhost.</p>';document.body.append(panel);});
