import { isHTML, resolvePath, relativePath, mimeType, dataURI, escapeHTML } from './core.js';
/** Resolves a virtual website without a server, leaving authored references recoverable. */
export class DocumentRuntime {
  constructor(model){this.model=model;this.cache=new Map();}
  asset(path){const file=this.model.get(path);if(!file)return null;const key=path+'\0'+file.content;const cached=this.cache.get(key);if(cached)return cached;const uri=file.kind==='data'?file.content:dataURI(new TextEncoder().encode(file.content),mimeType(path));if(this.cache.size>128)this.cache.clear();this.cache.set(key,uri);return uri;}
  css(text,path,visited=new Set()){
    if(visited.has(path))return '';visited=new Set(visited);visited.add(path);
    text=text.replace(/@import\s+(?:url\(\s*)?["']([^"']+)["']\s*\)?\s*([^;]*);/gi,(match,url,media)=>{const p=resolvePath(path,url),f=p&&this.model.get(p);if(!f)return match;const result=this.css(f.content,p,visited);return media.trim()?`@media ${media}{${result}}`:result;});
    return text.replace(/url\(\s*(["']?)([^)'"\s]+)\1\s*\)/gi,(match,quote,url)=>{const target=resolvePath(path,url),uri=target&&this.asset(target);return uri?`url("${uri}")`:match;});
  }
  prepare(path,{design=true,channel=''}={}){
    const file=this.model.get(path);const doc=new DOMParser().parseFromString(file?.content||'','text/html');
    for(const node of [...doc.querySelectorAll('base,meta[http-equiv]')]){if(node.tagName==='META'&&!/^(refresh|content-security-policy)$/i.test(node.httpEquiv))continue;const placeholder=doc.createElement('template');placeholder.dataset.pfPreserve='';placeholder.content.append(node.cloneNode(true));node.replaceWith(placeholder);}
    for(const link of [...doc.querySelectorAll('link[rel="stylesheet"][href]')]){const target=resolvePath(path,link.getAttribute('href'));const css=target&&this.model.get(target);if(css){const style=doc.createElement('style');style.dataset.pfRuntime='';style.textContent=this.css(css.content,target);if(link.media)style.media=link.media;link.after(style);link.dataset.pfHref=link.getAttribute('href');link.removeAttribute('href');}}
    for(const style of doc.querySelectorAll('style:not([data-pf-runtime])')){const original=style.textContent;const resolved=this.css(original,path);if(original!==resolved){style.dataset.pfCss=original;style.textContent=resolved;}}
    for(const element of doc.querySelectorAll('[src],[poster],[srcset]')){
      if(element.tagName==='SCRIPT')continue;
      for(const attr of ['src','poster'])if(element.hasAttribute(attr)){const original=element.getAttribute(attr),target=resolvePath(path,original),uri=target&&this.asset(target);if(uri){element.setAttribute('data-pf-'+attr,original);element.setAttribute(attr,uri);}}
      if(element.hasAttribute('srcset')){const original=element.getAttribute('srcset');element.dataset.pfSrcset=original;element.setAttribute('srcset',original.split(',').map(entry=>{const [url,...descriptor]=entry.trim().split(/\s+/),target=resolvePath(path,url);return [(target&&this.asset(target))||url,...descriptor].join(' ');}).join(', '));}
    }
    for(const script of [...doc.querySelectorAll('script')]){
      if(design){const placeholder=doc.createElement('template');placeholder.dataset.pfPreserve='';placeholder.content.append(script.cloneNode(true));script.replaceWith(placeholder);}
      else if(script.hasAttribute('src')){const target=resolvePath(path,script.getAttribute('src')),js=target&&this.model.get(target);if(js){script.removeAttribute('src');script.textContent=js.content;}}
    }
    const policy=doc.createElement('meta');policy.httpEquiv='Content-Security-Policy';policy.dataset.pfRuntime='';policy.content=`default-src 'none'; script-src ${design?"'none'":"'unsafe-inline' data: blob:"}; style-src 'unsafe-inline' data: blob: https:; img-src data: blob: https:; font-src data: blob: https:; media-src data: blob: https:; connect-src 'none'; object-src 'none'; frame-src 'none'; base-uri 'none'; form-action 'none'`;doc.head.prepend(policy);
    if(design){
      const style=doc.createElement('style');style.dataset.pfRuntime='';style.textContent='html{scroll-behavior:auto!important}body{min-height:calc(100vh - 2px);caret-color:#2868d8!important}*:focus{outline:none}a,button,input,textarea,select{cursor:text}::selection{background:#a9c9ff;color:inherit}table:empty,section:empty,div:empty,p:empty{min-height:24px}';doc.head.append(style);
    }else{
      for(const anchor of doc.querySelectorAll('a[href]')){const raw=anchor.getAttribute('href'),target=resolvePath(path,raw);if(target&&this.model.get(target)&&isHTML(target)){anchor.dataset.pfRoute=target;if(raw.includes('#'))anchor.dataset.pfHash=raw.slice(raw.indexOf('#'));}}
      const bridge=doc.createElement('script');bridge.dataset.pfRuntime='';bridge.textContent=`document.addEventListener('click',e=>{const a=e.target.closest('a[data-pf-route]');if(a){e.preventDefault();parent.postMessage({type:'pageforge:navigate',channel:${JSON.stringify(channel)},path:a.dataset.pfRoute,hash:a.dataset.pfHash||''},'*');}});window.addEventListener('error',e=>parent.postMessage({type:'pageforge:preview-error',channel:${JSON.stringify(channel)},message:e.message},'*'));`;doc.body.append(bridge);
    }
    return '<!DOCTYPE html>\n'+doc.documentElement.outerHTML;
  }
}
export class VisualEditor extends EventTarget {
  constructor(frame,model,runtime){super();this.frame=frame;this.model=model;this.runtime=runtime;this.doc=null;this.selected=null;this.range=null;this.timer=0;this.path=null;this.composing=false;this.generation=0;this.originalBodyEditable=null;this.originalBodySpellcheck=null;}
  emit(type,detail={}){this.dispatchEvent(new CustomEvent(type,{detail}));}
  async load(path,bookmark=null){this.flush();this.pendingLoadResolve?.();this.path=path;this.selected=null;this.range=null;this.doc=null;this.observer?.disconnect();const generation=++this.generation;return new Promise(resolve=>{this.pendingLoadResolve=resolve;this.frame.onload=()=>{if(generation!==this.generation){resolve();return;}this.doc=this.frame.contentDocument;if(!this.doc?.body){resolve();return;}this.originalBodyEditable=this.doc.body.getAttribute('contenteditable');this.originalBodySpellcheck=this.doc.body.getAttribute('spellcheck');this.doc.body.contentEditable='true';this.doc.body.spellcheck=true;this.bind();this.select(this.doc.querySelector('h1')||this.doc.body);if(bookmark)this.restoreBookmark(bookmark);this.emit('load');this.pendingLoadResolve=null;resolve();};this.frame.srcdoc=this.runtime.prepare(path,{design:true});});}
  bind(){const d=this.doc;
    d.addEventListener('click',e=>{const anchor=e.target.closest('a');if(anchor){e.preventDefault();if(e.ctrlKey||e.metaKey){const path=resolvePath(this.path,anchor.getAttribute('href'));if(path&&this.model.get(path))this.emit('navigate',{path});return;}}if(e.target.closest('button,input,textarea,select'))e.preventDefault();this.select(e.target.closest('img,td,th,button,input,textarea,select')||e.target);});
    d.addEventListener('dblclick',e=>{if(e.target.tagName==='IMG')this.emit('image',{element:e.target});});
    d.addEventListener('submit',e=>e.preventDefault());
    d.addEventListener('input',()=>{if(!this.composing)this.schedule();this.invalidate();});
    d.addEventListener('compositionstart',()=>{this.composing=true;});d.addEventListener('compositionend',()=>{this.composing=false;this.schedule();});
    d.addEventListener('beforeinput',e=>{if(e.inputType==='historyUndo'||e.inputType==='historyRedo'){e.preventDefault();this.emit('shortcut',{command:e.inputType==='historyUndo'?'undo':'redo'});}});
    d.addEventListener('selectionchange',()=>{const s=d.getSelection();if(s?.rangeCount&&d.body.contains(s.anchorNode)){this.range=s.getRangeAt(0).cloneRange();const el=s.anchorNode.nodeType===1?s.anchorNode:s.anchorNode.parentElement;if(el&&el!==d.body&&el!==this.selected&&!s.isCollapsed)this.select(el,false);this.emit('selection',{element:this.selected});}});
    d.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey;let command=null;if(mod){command=({s:'save',z:e.shiftKey?'redo':'undo',y:'redo',b:'bold',i:'italic',u:'underline',k:'link',f:'find'})[e.key.toLowerCase()];}if(command){e.preventDefault();this.emit('shortcut',{command});}if(e.key==='Escape'){this.select(this.selected?.parentElement||d.body);e.preventDefault();}if(e.key==='Tab'&&this.selected?.closest('table')){const cells=[...this.selected.closest('table').querySelectorAll('td,th')],current=this.selected.closest('td,th'),next=cells[cells.indexOf(current)+(e.shiftKey?-1:1)];if(next){e.preventDefault();this.select(next);const r=d.createRange();r.selectNodeContents(next);r.collapse(true);this.setRange(r);}}});
    d.addEventListener('paste',e=>{e.preventDefault();const html=e.clipboardData.getData('text/html'),text=e.clipboardData.getData('text/plain');if(html)this.insertHTML(this.sanitize(html),'Paste',true);else this.insertText(text);});
    d.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/x-pageforge-component')||e.dataTransfer.types.includes('application/x-pageforge-node'))e.preventDefault();});
    d.addEventListener('drop',e=>{const component=e.dataTransfer.getData('application/x-pageforge-component'),node=e.dataTransfer.getData('application/x-pageforge-node');if(component||node){e.preventDefault();this.select(e.target);if(component)this.emit('dropcomponent',{id:component});if(node)this.emit('dropnode',{path:JSON.parse(node),target:e.target});}});
    this.observer?.disconnect();this.observer=new MutationObserver(()=>this.invalidate());this.observer.observe(d.body,{subtree:true,childList:true,attributes:true,characterData:true});
    d.addEventListener('scroll',()=>this.invalidate(),true);d.addEventListener('load',()=>this.invalidate(),true);
    this.frame.contentWindow.addEventListener('resize',()=>this.invalidate());
  }
  select(element,saveRange=true){if(!element||!this.doc?.body.contains(element))element=this.doc?.body;if(!element)return;if(element.nodeType!==1)element=element.parentElement;this.selected=element;if(saveRange){const s=this.doc.getSelection();if(s?.rangeCount&&this.doc.body.contains(s.anchorNode))this.range=s.getRangeAt(0).cloneRange();}this.emit('selection',{element});this.invalidate();}
  invalidate(){this.emit('paint');}
  schedule(){clearTimeout(this.timer);this.timer=setTimeout(()=>this.commit('Typing'),300);}
  flush(){if(this.timer){clearTimeout(this.timer);this.timer=0;this.commit('Typing');}}
  serialize(){if(!this.doc)return this.model.get(this.path)?.content||'';const root=this.doc.documentElement.cloneNode(true);for(const node of root.querySelectorAll('[data-pf-runtime]'))node.remove();for(const template of root.querySelectorAll('template[data-pf-preserve]'))template.replaceWith(template.content.cloneNode(true));for(const element of root.querySelectorAll('*')){
      for(const attr of ['src','poster','href','srcset'])if(element.hasAttribute('data-pf-'+attr)){element.setAttribute(attr,element.getAttribute('data-pf-'+attr));element.removeAttribute('data-pf-'+attr);}
      if(element.hasAttribute('data-pf-css')){element.textContent=element.getAttribute('data-pf-css');element.removeAttribute('data-pf-css');}
    }
    const body=root.querySelector('body');if(this.originalBodyEditable===null)body.removeAttribute('contenteditable');else body.setAttribute('contenteditable',this.originalBodyEditable);if(this.originalBodySpellcheck===null)body.removeAttribute('spellcheck');else body.setAttribute('spellcheck',this.originalBodySpellcheck);
    return '<!DOCTYPE html>\n'+root.outerHTML;
  }
  commit(label){clearTimeout(this.timer);this.timer=0;if(!this.doc||!this.path||this.composing)return;const content=this.serialize();this.model.update(this.path,content,label,this.bookmark());this.emit('commit',{label});}
  transaction(label,action){if(!this.doc)return;this.flush();action();this.commit(label);this.emit('selection',{element:this.selected});this.invalidate();}
  nodePath(node){const path=[];while(node&&node!==this.doc.body){const p=node.parentNode;if(!p)return null;path.unshift([...p.childNodes].indexOf(node));node=p;}return node?path:null;}
  fromPath(path){let node=this.doc?.body;for(const index of path||[]){node=node?.childNodes[index];if(!node)return null;}return node;}
  bookmark(){const s=this.doc?.getSelection();if(!s?.rangeCount)return null;const r=s.getRangeAt(0),start=this.nodePath(r.startContainer),end=this.nodePath(r.endContainer);return start&&end?{start,end,startOffset:r.startOffset,endOffset:r.endOffset}:null;}
  restoreBookmark(b){try{const a=this.fromPath(b.start),z=this.fromPath(b.end);if(!a||!z)return;const r=this.doc.createRange();r.setStart(a,Math.min(b.startOffset,a.nodeType===3?a.length:a.childNodes.length));r.setEnd(z,Math.min(b.endOffset,z.nodeType===3?z.length:z.childNodes.length));this.setRange(r);}catch{}}
  setRange(range){this.doc.body.focus({preventScroll:true});const selection=this.doc.getSelection();selection.removeAllRanges();selection.addRange(range);this.range=range.cloneRange();}
  restoreRange(){if(this.range&&this.doc.body.contains(this.range.commonAncestorContainer)){this.setRange(this.range);return this.range;}return null;}
  block(){return this.selected?.closest('p,h1,h2,h3,h4,h5,h6,li,blockquote,td,th,div,section,article,header,footer')||this.selected||this.doc.body;}
  format(command,value){if(!this.doc)return;this.transaction('Format '+command,()=>{
    let target=this.selected||this.doc.body;const range=this.restoreRange();
    const tags={bold:'strong',italic:'em',underline:'u',strike:'s'};
    if(tags[command]){
      const tag=tags[command];const ancestor=target.closest(tag);
      if(ancestor&&(!range||range.collapsed||range.toString()===ancestor.textContent)){const parent=ancestor.parentElement;ancestor.replaceWith(...ancestor.childNodes);this.select(parent);}
      else if(range&&!range.collapsed){const wrapper=this.doc.createElement(tag);wrapper.append(range.extractContents());range.insertNode(wrapper);range.selectNodeContents(wrapper);this.setRange(range);this.select(wrapper,false);}
      else {const prop={bold:'fontWeight',italic:'fontStyle',underline:'textDecoration',strike:'textDecoration'}[command];const active={bold:'700',italic:'italic',underline:'underline',strike:'line-through'}[command];const computed=this.frame.contentWindow.getComputedStyle(target);target.style[prop]=(computed[prop]===active||(command==='bold'&&Number(computed.fontWeight)>=600))?({bold:'400',italic:'normal',underline:'none',strike:'none'}[command]):active;}
    }else if(command==='block'){
      const block=this.block();if(block===this.doc.body)return;const replacement=this.doc.createElement(value);for(const attr of block.attributes)replacement.setAttribute(attr.name,attr.value);replacement.append(...block.childNodes);block.replaceWith(replacement);this.select(replacement);
    }else if(command==='ul'||command==='ol'){
      const block=this.block(),existing=block.closest('ul,ol');if(existing){const fragment=this.doc.createDocumentFragment();for(const li of [...existing.children]){const p=this.doc.createElement('p');p.append(...li.childNodes);fragment.append(p);}const first=fragment.firstChild;existing.replaceWith(fragment);this.select(first);}else if(block!==this.doc.body){const list=this.doc.createElement(command),li=this.doc.createElement('li');li.append(...block.childNodes);list.append(li);block.replaceWith(list);this.select(li);}
    }else if(command==='indent'||command==='outdent'){target=this.block();const current=parseFloat(this.frame.contentWindow.getComputedStyle(target).marginInlineStart)||0;target.style.marginInlineStart=Math.max(0,current+(command==='indent'?24:-24))+'px';}
    else if(command==='clear'){if(range&&!range.collapsed){const text=this.doc.createTextNode(range.toString());range.deleteContents();range.insertNode(text);range.selectNodeContents(text);this.setRange(range);}else{target.removeAttribute('style');for(const el of [...target.querySelectorAll('strong,b,em,i,u,s,span')])el.replaceWith(...el.childNodes);}}
    else {const properties={left:'textAlign',center:'textAlign',right:'textAlign',justify:'textAlign',font:'fontFamily',size:'fontSize',color:'color',highlight:'backgroundColor'};const prop=properties[command];if(!prop)return;const val=['left','center','right','justify'].includes(command)?command:value;if(range&&!range.collapsed&&!['left','center','right','justify'].includes(command)){const span=this.doc.createElement('span');span.style[prop]=val;span.append(range.extractContents());range.insertNode(span);range.selectNodeContents(span);this.setRange(range);this.select(span,false);}else{target=['left','center','right','justify'].includes(command)?this.block():target;target.style[prop]=val;}}
  });}
  setProperty(name,value,isAttribute=false){const target=this.selected;if(!target)return;this.transaction('Set '+name,()=>{if(isAttribute){if(value==='')target.removeAttribute(name);else target.setAttribute(name,value);if(['src','poster'].includes(name)){target.removeAttribute('data-pf-'+name);const path=resolvePath(this.path,value),asset=path&&this.runtime.asset(path);if(asset){target.setAttribute('data-pf-'+name,value);target.setAttribute(name,asset);}}}else{if(value.trim()==='')target.style.removeProperty(name);else target.style.setProperty(name,value);}});}
  insertHTML(html,label='Insert element',atCaret=false){this.transaction(label,()=>{const template=this.doc.createElement('template');template.innerHTML=html;const nodes=[...template.content.childNodes];let first=nodes.find(n=>n.nodeType===1);if(atCaret){const range=this.restoreRange();if(range){range.deleteContents();range.insertNode(template.content);const last=nodes[nodes.length-1];if(last){range.setStartAfter(last);range.collapse(true);this.setRange(range);}}else this.doc.body.append(template.content);}else{const block=this.block();if(block===this.doc.body)this.doc.body.append(template.content);else{const container=block.closest('section,article,header,footer,figure,table');if(first&&['SECTION','ARTICLE','HEADER','FOOTER','FIGURE','TABLE'].includes(first.tagName)&&container)container.after(template.content);else block.after(template.content);}}if(first){this.resolveInserted(first);this.select(first);first.scrollIntoView({block:'nearest'});}});}
  resolveInserted(root){for(const el of [root,...root.querySelectorAll('[src]')])if(el.hasAttribute('src')){const raw=el.getAttribute('src'),path=resolvePath(this.path,raw),uri=path&&this.runtime.asset(path);if(uri){el.dataset.pfSrc=raw;el.setAttribute('src',uri);}}}
  insertText(text){this.transaction('Paste text',()=>{let range=this.restoreRange();if(!range){range=this.doc.createRange();range.selectNodeContents(this.selected||this.doc.body);range.collapse(false);}range.deleteContents();const node=this.doc.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);this.setRange(range);});}
  sanitize(html){const parsed=new DOMParser().parseFromString(html,'text/html');parsed.querySelectorAll('script,style,iframe,object,embed,link,meta,base,form,input,button,textarea,select').forEach(n=>n.remove());for(const el of parsed.body.querySelectorAll('*')){for(const a of [...el.attributes])if(/^on/i.test(a.name)||a.name==='srcdoc'||a.name==='contenteditable'||a.name.startsWith('data-pf-')||(['href','src'].includes(a.name)&&/^\s*(javascript|vbscript|data:text\/html):/i.test(a.value)))el.removeAttribute(a.name);}return parsed.body.innerHTML;}
  link(href,text='',newTab=false){if(/^\s*(javascript|vbscript|data):/i.test(href))throw new Error('Use an https, mailto, tel, anchor, or project URL.');this.transaction('Insert hyperlink',()=>{let a=this.selected?.closest('a'),range=this.restoreRange();if(a){a.setAttribute('href',href);if(text)a.textContent=text;}else{a=this.doc.createElement('a');a.href=href;if(range&&!range.collapsed){a.append(range.extractContents());range.insertNode(a);}else{a.textContent=text||href;if(range){range.insertNode(a);range.setStartAfter(a);range.collapse(true);this.setRange(range);}else (this.selected||this.doc.body).append(a);}}if(newTab){a.target='_blank';a.rel='noopener noreferrer';}else{a.removeAttribute('target');a.removeAttribute('rel');}this.select(a);});}
  duplicate(){if(!this.selected||this.selected===this.doc.body)return;this.transaction('Duplicate element',()=>{const clone=this.selected.cloneNode(true);clone.removeAttribute('id');clone.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));this.selected.after(clone);this.select(clone);});}
  remove(){if(!this.selected||this.selected===this.doc.body)return;this.transaction('Delete element',()=>{const parent=this.selected.parentElement;this.selected.remove();this.select(parent);});}
  move(direction){if(!this.selected||this.selected===this.doc.body)return;this.transaction('Move element',()=>{const el=this.selected,sibling=direction<0?el.previousElementSibling:el.nextElementSibling;if(sibling){if(direction<0)sibling.before(el);else sibling.after(el);el.scrollIntoView({block:'nearest'});}});}
  moveNode(path,target){const node=this.fromPath(path);if(!node||node===this.doc.body||node===target||node.contains(target))return;this.transaction('Move element',()=>{if(target===this.doc.body)target.append(node);else target.after(node);this.select(node);});}
  table(action){const table=this.selected?.closest('table');if(!table)throw new Error('Select a table cell first.');this.transaction('Table '+action,()=>{const cell=this.selected.closest('td,th'),row=cell?.parentElement||table.rows[0];if(!row)return;const col=cell?.cellIndex||0;if(action==='row'){const newRow=row.cloneNode(true);for(const c of newRow.cells){c.textContent='Cell';c.removeAttribute('id');}row.after(newRow);this.select(newRow.cells[0]);}else if(action==='column'){for(const r of table.rows){const c=this.doc.createElement(r.cells[0]?.tagName||'td');c.textContent='Cell';r.cells[Math.min(col,r.cells.length-1)]?.after(c);}}else if(action==='delete-row'){if(table.rows.length===1){table.remove();this.select(this.doc.body);}else{const next=row.nextElementSibling||row.previousElementSibling;row.remove();this.select(next?.cells[0]||table);}}else if(action==='delete-column'){for(const r of [...table.rows])r.cells[col]?.remove();if([...table.rows].every(r=>!r.cells.length)){table.remove();this.select(this.doc.body);}else this.select(table.querySelector('td,th')||table);}});}
  dispose(){this.flush();this.observer?.disconnect();this.generation++;}
}
