import { normalizePath, LIMITS } from './core.js';
const crcTable=Uint32Array.from({length:256},(_,i)=>{let c=i;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
export function crc32(bytes){let crc=0xffffffff;for(const b of bytes)crc=crcTable[(crc^b)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}
/** ZIP32, UTF-8 names, stored entries. Standards-compatible; no external library. */
export function createZip(entries){const encoder=new TextEncoder();const chunks=[],central=[];let offset=0,centralSize=0;const now=new Date();const time=(now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1),date=((Math.max(1980,now.getFullYear())-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate();
  for(const entry of entries){const name=encoder.encode(normalizePath(entry.path)),bytes=entry.bytes instanceof Uint8Array?entry.bytes:encoder.encode(entry.content||'');const crc=crc32(bytes);const local=new Uint8Array(30+name.length);const d=new DataView(local.buffer);d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(6,0x800,true);d.setUint16(10,time,true);d.setUint16(12,date,true);d.setUint32(14,crc,true);d.setUint32(18,bytes.length,true);d.setUint32(22,bytes.length,true);d.setUint16(26,name.length,true);local.set(name,30);chunks.push(local,bytes);
    const c=new Uint8Array(46+name.length),v=new DataView(c.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x800,true);v.setUint16(12,time,true);v.setUint16(14,date,true);v.setUint32(16,crc,true);v.setUint32(20,bytes.length,true);v.setUint32(24,bytes.length,true);v.setUint16(28,name.length,true);v.setUint32(42,offset,true);c.set(name,46);central.push(c);centralSize+=c.length;offset+=local.length+bytes.length;
  }
  const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,centralSize,true);v.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'});
}
export async function readZip(buffer){const bytes=new Uint8Array(buffer),v=new DataView(buffer);if(bytes.length>LIMITS.projectBytes)throw new Error('Archive exceeds 48 MB.');let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(v.getUint32(i,true)===0x06054b50){end=i;break;}if(end<0)throw new Error('Not a valid ZIP archive.');if(v.getUint16(end+4,true)||v.getUint16(end+6,true))throw new Error('Multi-volume ZIP is not supported.');const count=v.getUint16(end+10,true);if(count>LIMITS.files)throw new Error('Too many files in ZIP.');let cursor=v.getUint32(end+16,true),total=0;const files=[],seen=new Set();
  for(let i=0;i<count;i++){if(cursor+46>bytes.length||v.getUint32(cursor,true)!==0x02014b50)throw new Error('Invalid ZIP directory.');const flags=v.getUint16(cursor+8,true),method=v.getUint16(cursor+10,true),crc=v.getUint32(cursor+16,true),packed=v.getUint32(cursor+20,true),size=v.getUint32(cursor+24,true),n=v.getUint16(cursor+28,true),x=v.getUint16(cursor+30,true),c=v.getUint16(cursor+32,true),off=v.getUint32(cursor+42,true);if(cursor+46+n+x+c>bytes.length)throw new Error('Truncated ZIP directory.');const name=new TextDecoder().decode(bytes.subarray(cursor+46,cursor+46+n));cursor+=46+n+x+c;if(name.endsWith('/'))continue;const path=normalizePath(name);if(seen.has(path))throw new Error('Duplicate ZIP entry: '+path);seen.add(path);total+=size;if(size>LIMITS.fileBytes||total>LIMITS.projectBytes)throw new Error('ZIP expansion exceeds safe limits.');if(flags&1)throw new Error('Encrypted ZIP is not supported.');if(off+30>bytes.length||v.getUint32(off,true)!==0x04034b50)throw new Error('Invalid ZIP local header.');const start=off+30+v.getUint16(off+26,true)+v.getUint16(off+28,true);if(start+packed>bytes.length)throw new Error('Truncated ZIP entry.');let data=bytes.slice(start,start+packed);if(method===8){if(typeof DecompressionStream==='undefined')throw new Error('This browser cannot decompress ZIP. Import individual files instead.');const reader=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader();const chunks=[];let length=0;while(true){const {value,done}=await reader.read();if(done)break;length+=value.length;if(length>size||length>LIMITS.fileBytes){await reader.cancel();throw new Error('ZIP expansion limit exceeded.');}chunks.push(value);}data=new Uint8Array(length);let p=0;for(const chunk of chunks){data.set(chunk,p);p+=chunk.length;}}else if(method!==0)throw new Error('Unsupported ZIP compression method: '+method);if(data.length!==size||crc32(data)!==crc)throw new Error('ZIP integrity check failed: '+path);files.push({path,bytes:data});}
  return files;
}
